BrokenIRC: server_src/channel_list.c File Reference
channel_list.c File Reference
#include "../include/server.h"
#include <stdlib.h>
Functions
t_channel * get_new_chan_list (t_userlist *userlist, char *channame)
void * insert_back_channel (t_channel *head, t_channel *new)
void remove_channel (t_channel *list, char *channame)
void free_channel_list (t_channel *list)
t_channel * init_default_channel ()
Function Documentation
free_channel_list()
void free_channel_list (t_channel * list)
Self explanatory
Parameters
list the list to be de-allocated
Definition at line 74 of file channel_list.c.
References free_userlist(), t_channel::next, and t_channel::users.
 {
         while (list) {
                 free_userlist(list->users);
                 t_channel *next = list->next;
                 free(list);
                 list = next;
         }
 }
get_new_chan_list()
t_channel* get_new_chan_list (t_userlist * userlist, char * channame)
Self explanatory
Parameters
userlist the userlist to insert in the new channel element
channame the new channel name
Definition at line 15 of file channel_list.c.
References t_channel::channame, t_channel::next, t_channel::prev, and t_channel::users.
Referenced by join().
 {
         t_channel *list = malloc(sizeof(*list));
         if (list) {
                 memset(list, 0, sizeof(*list));
                 list->users = userlist;
                 list->channame = strdup(channame);
                 list->prev = NULL;
                 list->next = NULL;
         }
         return (list);
 }
init_default_channel()
t_channel* init_default_channel ()
Self explanatory
Returns
the default channel where all user resides
Note
the channel name, the default user and all could be parsed from a config file (#pullrequestIdea)
Definition at line 89 of file channel_list.c.
References t_channel::channame, get_new_user(), get_new_userlist(), t_channel::next, t_channel::prev, and t_channel::users.
Referenced by get_methods().
 {
         char *defuser[5] = {"NICK", "4Dm1n", "42", "*", ":John Doe"};
         t_channel *defchan = malloc(sizeof(*defchan));
         t_user *admin = get_new_user(0, defuser);
         t_userlist *allusers = get_new_userlist(admin);
         if (defchan && admin && allusers) {
                 defchan->channame = "#welcome";
                 defchan->users = allusers;
                 defchan->prev = NULL;
                 defchan->next = NULL;
         }
         return (defchan);
 }
insert_back_channel()
void* insert_back_channel (t_channel * head, t_channel * new)
Push back a new channel element to the main list container
Parameters
head the head pointer
new the new channel element to be inserted
Definition at line 33 of file channel_list.c.
References t_channel::next.
Referenced by join().
 {
         t_channel *tmp = head;
         if (!head) {
                 head = new;
         } else {
                 while (tmp->next) {
                         tmp = tmp->next;
                 }
                 tmp->next = new;
                 new->prev = tmp;
         }
         return (head);
 }
remove_channel()
void remove_channel (t_channel * list, char * channame)
Remove a channel element from the doubly linked list
Parameters
list the userlist to be updated
channame the channel name to be deleted
Definition at line 53 of file channel_list.c.
References t_channel::channame, free_userlist(), t_channel::next, t_channel::prev, and t_channel::users.
 {
         t_channel *tmp = list;
         while (tmp->next != NULL)
         {
                 if (!strcmp(tmp->channame, channame)) {
                         tmp->prev->next = tmp->next;
                         tmp->next->prev = tmp->prev;
                         free_userlist(tmp->users);
                         free(tmp->channame);
                         free(tmp);
                         break;
                 }
                 tmp = tmp->next;
         }
 }