PSU_zappy_2017: server/src/commandline_args_handlers/cl_args_helpers.c File Reference
cl_args_helpers.c File Reference
#include <stdlib.h>
#include "../../include/server.h"
Functions
void * error_exit (t_clargs *args, clargs *opts, char *req_save)
void * clean_exit (t_clargs *args, clargs *opts, char *req_save)
void free_opts (t_clargs *opts)
void free_buffers (char **buffer)
clargs * set_opts ()
Function Documentation
clean_exit()
void* clean_exit (t_clargs * args, clargs * opts, char * req_save)
Definition at line 19 of file cl_args_helpers.c.
Referenced by get_opts().
 {
         free(opts);
         free(req_save);
         return args;
 }
error_exit()
void* error_exit (t_clargs * args, clargs * opts, char * req_save)
Definition at line 11 of file cl_args_helpers.c.
Referenced by get_opts().
 {
         free(args);
         free(opts);
         free(req_save);
         return NULL;
 }
free_buffers()
void free_buffers (char ** buffer)
Free the token list
Parameters
buffer the 2D array to be free'd
Definition at line 42 of file cl_args_helpers.c.
Referenced by free_opts(), get_methods(), and get_opts().
 {
         int i;
         for (i = 0; buffer[i]; ++i) {
                 free(buffer[i]);
         }
         free(buffer);
 }
free_opts()
void free_opts (t_clargs * opts)
Free the t_clargs structure
Parameters
opts the structure
Definition at line 30 of file cl_args_helpers.c.
References free_buffers(), t_clargs::port, and t_clargs::teams_names.
 {
         if (opts) {
                 free(opts->port);
                 free_buffers(opts->teams_names);
                 free(opts);
         }
 }
set_opts()
clargs* set_opts ()
The flags 'gatherer' initialiser
Returns
opts the flags function pointer malloc'ed and assigned
Definition at line 55 of file cl_args_helpers.c.
References get_clientsNb(), get_freq(), get_height(), get_port(), get_teams(), and get_width().
Referenced by get_opts().
 {
         clargs *opts = malloc(sizeof(clargs) * 'z');
         opts['p'] = get_port;
         opts['x'] = get_width;
         opts['y'] = get_height;
         opts['n'] = get_teams;
         opts['c'] = get_clientsNb;
         opts['f'] = get_freq;
         return (opts);
 }