PSU_zappy_2017Server: server_src/command_line_args/cl_flags_bis.c File Reference
cl_flags_bis.c File Reference
#include <stdlib.h>
#include "../../include/server.h"
Functions
void * get_teams (char **teams, t_clargs *args)
void * get_clientsNb (char **clientsNb, t_clargs *args)
void * get_freq (char **freq, t_clargs *args)
Function Documentation
get_clientsNb()
void* get_clientsNb (char ** clientsNb, t_clargs * args)
Get -c flag, the number of clients(aka players) per teams
Parameters
clientsNb the received arguments to flag
args the t_clargs struct to fill with clientsNb value
Definition at line 33 of file cl_flags_bis.c.
References t_clargs::clientsNb.
Referenced by set_opts().
 {
         #ifdef CLDBG
                 printf("\t%s\n", "get_clientsNb ouh yeah!");
                 print_2d(clientsNb);
         #endif
         args->clientsNb = atoi(clientsNb[1]);
         return (args->clientsNb >= 0 ? args : NULL);
 }
get_freq()
void* get_freq (char ** freq, t_clargs * args)
Get -f flag, the frequency of blablabla
Parameters
freq the received argument to flag
args the t_clargs struct to fill with frequency value
Definition at line 47 of file cl_flags_bis.c.
References t_clargs::freq.
Referenced by set_opts().
 {
         #ifdef CLDBG
                 printf("\t%s\n", "get_freq ouh yeah!");
                 print_2d(freq);
         #endif
         args->freq = atoi(freq[1]);
         return (args->freq >= 0 ? args : NULL);
 }
get_teams()
void* get_teams (char ** teams, t_clargs * args)
Get -n flag, the teams name
Parameters
teams the received argument to flag
args the t_clargs struct to fill with teams names values
Definition at line 15 of file cl_flags_bis.c.
References MAXTEAMS, and t_clargs::teams_names.
Referenced by set_opts().
 {
         unsigned int size = 0;
         #ifdef CLDBG
                 printf("\t%s\n", "get_teams ouh yeah!");
                 print_2d(teams);
         #endif
         args->teams_names = malloc(MAXTEAMS);
         for (size = 1; teams[size]; ++size) {
                 args->teams_names[size - 1] = strdup(teams[size]);
         }
         return (size > 0 ? args : NULL);
 }