PSU_zappy_2017: server/src/commandline_args_handlers/cl_args_parsing.c File Reference
cl_args_parsing.c File Reference
#include <stdlib.h>
#include <stdbool.h>
#include "server.h"
Functions
static bool check_opts (char **av)
static char ** get_cmdargs (char *buff, char **saveptr)
static char * get_req (unsigned int ac, char **av)
static t_clargs * set_default_args ()
t_clargs * get_opts (int ac, char **av)
Function Documentation
check_opts()
static bool check_opts (char ** av) static
Check if all flags are present in command line arguments from main()
Parameters
av the 2D char array from main()
Returns
true if all flags are presents
false if there is any problem
Definition at line 17 of file cl_args_parsing.c.
Referenced by get_opts().
 {
         int             i = 1;
         int             j = 0;
         int             k = 0;
         char            flags_cnt[6] = "\0";
         const char      *flags[5] = {"-p", "-x", "-y", "-n", "-c"};
         for (; av[i]; ++i) {
                 for (j = 0; j <= 4; ++j) {
                         if (!strcmp(av[i], flags[j])) {
                                 flags_cnt[k] = av[i][1];
                                 ++k;
                                 break;
                         }
                 }
         }
         return (strstr(flags_cnt, "pxync") ? true : false);
 }
get_cmdargs()
static char** get_cmdargs (char * buff, char ** saveptr) static
Tokenize the flag buffer, splitting by spaces
Parameters
buff a command string like "-[x] [args]"
saveptr the requested strtok_r context saving pointer
Returns
cmd_args the flags arguments
Definition at line 42 of file cl_args_parsing.c.
Referenced by get_opts().
 {
         char *subtoken = NULL;
         char **cmd_args = malloc(2048);
         unsigned int size = 0;
         if (cmd_args) {
                 memset(cmd_args, 0, 2048);
                 for (; ; buff = NULL) {
                         subtoken = strtok_r(buff, " ", saveptr);
                         if (subtoken == NULL)
                                 break;
                         cmd_args[size] = strdup(subtoken);
                         size = size + 1 <= 2048 ? size + 1 : size;
                 }
                 cmd_args[size] = NULL;
         }
         return (cmd_args);
 }
get_opts()
t_clargs* get_opts (int ac, char ** av)
Parse command line args flags from av[] and store it in a t_clargs struct
Parameters
ac the number of received params
av the 2d char array from main()
Returns
args the storage struct
NULL if errors
Todo:
Consider refactoring / splitting this function as it's 4 lines above the 20's authorized. Variables are also uncorrectly declared. solution ? do a 'trash bin struct' for all args and catch them all !
Add free() for all the malloc'ed buffers
Definition at line 108 of file cl_args_parsing.c.
References check_opts(), clean_exit(), error_exit(), free_buffers(), get_cmdargs(), get_req(), set_default_args(), and set_opts().
Referenced by main().
 {
         t_clargs        *args = set_default_args();
         char            *req = get_req(ac, av);
         clargs          *opts = set_opts();
         char            *saveptr1, *saveptr2;
         char            **cmd_args = NULL;
         char            *req_save = req;
         int             index = 0;
         char            *token;
         if (args && req && check_opts(av)) {
                 for (; ; req = NULL) {
                         token = strtok_r(req, "-", &saveptr1);
                         if (token == NULL) {
                                 break;
                         } else {
                                 index = token[0];
                                 cmd_args = get_cmdargs(token, &saveptr2);
                                 cmd_args ? opts[index](cmd_args, args) : opts;
                                 cmd_args ? free_buffers(cmd_args) : cmd_args;
                         }
                 }
         }
         return (check_opts(av) ? clean_exit(args, opts, req_save) :
                 error_exit(args, opts, req_save));
 }
get_req()
static char* get_req (unsigned int ac, char ** av) static
Construct a single string from av args for an easiest parsing
Parameters
ac the number of received args
av the command line option from main()
Returns
req the string with all args
Definition at line 67 of file cl_args_parsing.c.
Referenced by get_opts().
 {
         char    *req = malloc(2048);
         unsigned int size = 0;
         uint    req_size = 0;
         memset(req, 0, 2048);
         if (ac >= 10 && req) {
                 for (size = 1; av[size]; ++size) {
                         strncat(req, av[size], strlen(av[size]));
                         size != ac - 1 ? strcat(req, " ") : req;
                 }
         }
         req_size = strlen(req);
         req_size <= 0 ? free(req) : req;
         return (req_size <= 0 ? NULL : req);
 }
set_default_args()
static t_clargs* set_default_args () static
Set default params for frequency argument
Returns
args a malloc'ed t_clargs struct with args-freq set to dflt value
Definition at line 88 of file cl_args_parsing.c.
References t_clargs::freq.
Referenced by get_opts().
 {
         t_clargs        *args = malloc(sizeof(*args));
         if (args) {
                 args->freq = 100;
         }
         return (args);
 }