PSU_zappy_2017: server_src/commandline_args_handlers/cl_flags.c File Reference
cl_flags.c File Reference
#include <stdlib.h>
#include "../include/server.h"
Functions
void * get_port (char **port, t_clargs *args)
void * get_width (char **width, t_clargs *args)
void * get_height (char **height, t_clargs *args)
Function Documentation
get_height()
void* get_height (char ** height, t_clargs * args)
Get -y flag, the map height
Parameters
height the received argument to flag
args the t_clargs struct to fill with height value
Definition at line 45 of file cl_flags.c.
References t_clargs::height.
Referenced by set_opts().
 {
         #ifdef CLDBG
                 printf("\t%s\n", "get_height ouh yeah!");
                 print_2d(height);
         #endif
         args->height = atoi(height[1]);
         return (args->height >= 0 ? args : NULL);
 }
get_port()
void* get_port (char ** port, t_clargs * args)
Get -p flag, the requested listening port for server
Parameters
port the received argument to flag
args the t_clargs struct to fill with port value
Definition at line 15 of file cl_flags.c.
References t_clargs::port.
Referenced by set_opts().
 {
         int rt = 0;
         #ifdef CLDBG
                 printf("\t\t%s\n", "get_port()");
                 print_2d(port);
         #endif
         args->port = strdup(port[1]);
         rt = atoi(port[1]);
         return (rt >= 1024 ? args : NULL);
 }
get_width()
void* get_width (char ** width, t_clargs * args)
Get -x flag, the map width
Parameters
width the received argument to flag
args the t_clargs struct to fill with width value
Definition at line 31 of file cl_flags.c.
References t_clargs::width.
Referenced by set_opts().
 {
         #ifdef CLDBG
                 printf("\t\t%s\n", "get_width()");
                 print_2d(width);
         #endif
         args->width = atoi(width[1]);
         return (args->width >= 0 ? args : NULL);
 }