PSU_zappy_2017: Network Class Reference
Network Class Reference
#include <Network_Client.hpp>
Public Member Functions
Network ()
~Network ()
std::vector< std::string > _look ()
std::vector< std::string > _fork ()
std::map< std::string, std::string > _teams (std::string team_name)
std::map< std::string, std::string > _forward ()
bool listen_up ()
std::map< std::string, std::string > get_map_size ()
std::vector< std::string > get_teamnames ()
std::vector< std::map< std::string, std::string > > get_team_details (std::string team)
std::string get_lastbuffer ()
bool connect_to (std::string server_host, std::string server_port)
Detailed Description
Definition at line 30 of file Network_Client.hpp.
Constructor & Destructor Documentation
Network()
Network::Network ()
Definition at line 10 of file Network_Client.cpp.
References MAX_RESP.
                  :  _server_port(2222), _server_host("127.0.0.1"),
         _addr((const struct sockaddr *)&_client_address)
 {
         memset(&_client_address, 0, sizeof(_client_address));
         memset(_server_resp, 0, MAX_RESP);
 }
~Network()
Network::~Network ()
Definition at line 17 of file Network_Client.cpp.
 {
         close(_client_socket);
 }
Member Function Documentation
_fork()
std::vector< std::string > Network::_fork ()
Definition at line 150 of file Network_Client.cpp.
References listen_up().
Referenced by Trantorian::_do_fork().
 {
         std::vector<std::string> res;
         std::string req("Fork\n");
         write(_client_socket, req.c_str(), req.size());
         listen_up();
         return (res);
 }
_forward()
std::map< std::string, std::string > Network::_forward ()
Definition at line 137 of file Network_Client.cpp.
References listen_up().
Referenced by Trantorian::_do_moove().
 {
         std::map<std::string, std::string> rt;
         std::string req("Forward\n");
         write(_client_socket, req.c_str(), req.size());
         listen_up();
         while (!_queue.empty()) {
                 _queue.pop();
         }
         return (rt);
 }
_look()
std::vector< std::string > Network::_look ()
Definition at line 123 of file Network_Client.cpp.
References listen_up().
Referenced by Trantorian::_do_search().
 {
         std::vector<std::string> rt;
         std::string req("Look\n");
         write(_client_socket, req.c_str(), req.size());
         listen_up();
         while (!_queue.empty()) {
                 rt.emplace_back(_queue.front());
                 _queue.pop();
         }
         return (rt);
 }
_teams()
std::map< std::string, std::string > Network::_teams (std::string team_name)
Definition at line 160 of file Network_Client.cpp.
References listen_up().
Referenced by Trantorian::_do_drop().
 {
         std::map<std::string, std::string> pos;
         std::string req("Team " + team_name + "\n");
         write(_client_socket, req.c_str(), req.size());
         listen_up();
         while (!_queue.empty()) {
                 std::string value(_queue.front());
                 if (value != "ko") {
                         pos["PLAYER_CREDIT"] = value;
                         _queue.pop();
                         value = _queue.front();
                         pos["x"] = value;
                         _queue.pop();
                         value = _queue.front();
                         pos["y"] = value;
                         break;
                 } else {
                         pos["ko"] = "NO CREDITS";
                 }
                 if (!_queue.empty())
                         _queue.pop();
         }
         return (pos);
 }
connect_to()
bool Network::connect_to (std::string server_host, std::string server_port)
Definition at line 22 of file Network_Client.cpp.
Referenced by Trantorian::check_co(), get_map_size(), get_team_details(), and get_teamnames().
 {
         int rt = 0;
         uint address_size = sizeof(_client_address);
         _server_port = std::stoi (server_port, nullptr, 10);
         strncpy(_server_host, server_host.c_str(), 45);
         _client_address.sin_family = AF_INET;
         _client_address.sin_addr.s_addr = inet_addr(_server_host);
         _client_address.sin_port = htons(_server_port);
         if ((_client_socket = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
                 std::cerr << "Nework(): socket() :" << strerror(errno) << "\n";
                 exit(EXIT_FAILURE);
         } else if ((rt = connect(_client_socket, _addr, address_size)) == -1) {
                 std::cerr << "connect: connect() :" << strerror(errno) << "\n";
         }
         return (rt >= 0 ? true : false);
 }
get_lastbuffer()
std::string Network::get_lastbuffer ()
Definition at line 211 of file Network_Client.cpp.
 {
         return _queue.front();
 }
get_map_size()
std::map< std::string, std::string > Network::get_map_size ()
Definition at line 41 of file Network_Client.cpp.
References connect_to(), and listen_up().
 {
         std::map<std::string, std::string> map_size;
         std::string req("GET /mapsize\n");
         if (!connect_to("127.0.0.1", "2222")) {
                 map_size["error"] = "Connection error";
         } else {
                 write(_client_socket, req.c_str(), req.size());
                 listen_up();
                 _queue.pop();
                 while (!_queue.empty()) {
                         if (_queue.front() != ",") {
                                 std::string index = _queue.front();
                                 _queue.pop();
                                 std::string value = _queue.front();
                                 map_size[index] = value;
                         }
                         _queue.pop();
                 }
         }
         return (map_size);
 }
get_team_details()
std::vector< std::map< std::string, std::string > > Network::get_team_details (std::string team)
Definition at line 87 of file Network_Client.cpp.
References connect_to(), and listen_up().
 {
         std::vector<std::map<std::string, std::string> > team_details;
         std::map<std::string, std::string>              player;
         std::string req("POST /team_detail&team=" + team + "\n");
         if (!connect_to("127.0.0.1", "2222")) {
                 std::map<std::string, std::string> err;
                 err["error"] = "Connection lost";
                 team_details.emplace_back(err);
         } else {
                 write(_client_socket, req.c_str(), req.size());
                 listen_up();
                 std::map<std::string, std::string> team_name;
                 team_name["teamname"] = _queue.front();
                 team_details.emplace_back(team_name);
                 _queue.pop();
                 while (!_queue.empty()) {
                         if (_queue.front() != ",") {
                                 std::string index = _queue.front();
                                 _queue.pop();
                                 std::string value = _queue.front();
                                 player[index] = value;
                         }
                         if (player.size() == 4) {
                                 team_details.emplace_back(player);
                                 player.clear();
                         }
                         _queue.pop();
                 }
         }
         return (team_details);
 }
get_teamnames()
std::vector< std::string > Network::get_teamnames ()
Definition at line 66 of file Network_Client.cpp.
References connect_to(), and listen_up().
 {
         std::vector<std::string> teams;
         std::string req("GET /teamnames\n");
         if (!connect_to("127.0.0.1", "2222")) {
                 teams.emplace_back("Connection error");
         } else {
                 write(_client_socket, req.c_str(), req.size());
                 listen_up();
                 while (!_queue.empty()) {
                         if (_queue.front() != "teamnames" && _queue.front() != ",") {
                                 teams.emplace_back(_queue.front());
                         }
                         _queue.pop();
                 }
         }
         return (teams);
 }
listen_up()
bool Network::listen_up ()
Definition at line 188 of file Network_Client.cpp.
References MAX_RESP.
Referenced by _fork(), _forward(), _look(), _teams(), get_map_size(), get_team_details(), and get_teamnames().
 {
         int r_size = 0;
         std::string s;
         std::regex r("[a-z0-9,.]+");
         memset(_server_resp, 0, MAX_RESP);
         while ((r_size = read(_client_socket, _server_resp, MAX_RESP)) > 0) {
                 if (r_size) {
                         s = _server_resp;
                         std::sregex_iterator i;
                         for (i = std::sregex_iterator(s.begin(), s.end(), r);
                         i != std::sregex_iterator(); ++i) {
                                 std::smatch m = *i;
                                 _queue.push(m.str());
                         }
                         break;
                 } else
                         break;
         }
         return (r_size > 0 ? true : false);
 }
The documentation for this class was generated from the following files:
client/commons/include/Network_Client.hpp
client/commons/src/Network_Client.cpp