PSU_zappy_2017: Trantorian Class Reference
Trantorian Class Reference
#include <Trantorian.hpp>
Public Member Functions
Trantorian (std::string server_port, std::string server_host)
~Trantorian ()
bool check_co ()
void _do_fork ()
void _do_moove ()
bool _do_drop ()
bool run (std::string team_name)
void _do_search (uint cnt)
Detailed Description
The main AI class
Definition at line 43 of file Trantorian.hpp.
Constructor & Destructor Documentation
Trantorian()
Trantorian::Trantorian (std::string server_port, std::string server_host)
The AI constructor
Parameters
server_port the zappy_server port
server_host the zappy_server address
Definition at line 14 of file Trantorian.cpp.
                                                                    :
 _server_port(server_port), _server_host(server_host)
 {
         _level = 1;
 }
~Trantorian()
Trantorian::~Trantorian ()
Definition at line 20 of file Trantorian.cpp.
 {
 }
Member Function Documentation
_do_drop()
bool Trantorian::_do_drop ()
The DROPPING state method , send Teams [teamname] command to server and parse response. Exit if MAX_PLAYER per team value is reached
Definition at line 86 of file Trantorian.cpp.
References EXIT_MAX_PLAYER, Network::get_map_dimension(), and log_drop().
Referenced by run().
 {
         bool rt = false;
         std::map<std::string, std::string> resp;
         resp = _client.get_map_dimension(_team_name);
         if (resp.find("x") != resp.end()
         && resp.find("y") != resp.end()
         && resp.find("PLAYER_CREDIT") != resp.end()) {
                 _map_size.push_back(std::stoi (resp["x"], nullptr, 10));
                 _map_size.push_back(std::stoi (resp["y"], nullptr, 10));
                 log_drop(resp, _map_size, _team_name);
                 rt = true;
         } else if (resp.find("ko") != resp.end()) {
                 std::cerr << "Error : reaching MAX PLAYER for team "
                 << _team_name << "\n";
                 exit(EXIT_MAX_PLAYER);
         }
         return (rt);
 }
_do_fork()
void Trantorian::_do_fork ()
The SEARCHING state method, send Fork command to server and if server respond ok, call fork() and launch a new Trantorian teammate in the child process
Definition at line 129 of file Trantorian.cpp.
References check_co(), Network::fork(), and run().
Referenced by run().
 {
         static uint childs;
         std::vector<std::string> resp;
         childs += 1;
         resp = _client.fork();
         if (fork() == 0) {
                 std::cerr << " Where in child n°" << childs << '\n';
                 Trantorian ia_player(_server_port, _server_host);
                 bool check = ia_player.check_co();
                 if (check) {
                         ia_player.run(_team_name);
                 }
         }
 }
_do_moove()
void Trantorian::_do_moove ()
Definition at line 146 of file Trantorian.cpp.
References Network::forward().
Referenced by run().
 {
         std::map<std::string, std::string> resp;
         std::cerr << "state : " << "MOOVING\n";
         std::cerr << "Send Forward on trantor map \n";
         std::cerr << "Note : we're still on level [";
         std::cerr << _level << "]\n";
         resp = _client.forward();
         std::cerr << "send -->Forward \n";
 }
_do_search()
void Trantorian::_do_search (uint cnt)
The SEARCHING state method, send Look command to server and (not yet) parse the response
Definition at line 110 of file Trantorian.cpp.
References Network::look(), and TTL.
Referenced by run().
 {
         std::vector<std::string> res = _client.look();
         std::cerr << "state : " << "SEARCHING\n";
         std::cerr << "send -->look \n";
         std::cerr << "Receive :\n";
         for (uint i = 0; i != res.size(); ++i) {
                 std::cerr << "[" << res[i] << "]\n";
         }
         if (cnt >= TTL) {
                 std::cerr << "No more life exiting..\n";
                 kill(getpid(), SIGINT);
         }
 }
check_co()
bool Trantorian::check_co ()
Utility function around the Trantorian::_client connect_to method
Returns
true if connection succedded
false if not
Definition at line 29 of file Trantorian.cpp.
References Network::connect_to().
Referenced by _do_fork(), and main().
 {
         bool rt = false;
         rt = _client.connect_to(_server_host, _server_port);
         return (rt);
 }
run()
bool Trantorian::run (std::string team_name)
The main AI event loop
Parameters
team_name the new Trantorian team name
Note
this stupid AI do only one thing, forward, forward and forward again until death
Definition at line 163 of file Trantorian.cpp.
References _do_drop(), _do_fork(), _do_moove(), _do_search(), DROPPING, EVER, FORKING, Frequency, MOOVING, PICKING_FOOD, PICKING_STONE, print_state(), and SEARCHING.
Referenced by _do_fork(), and main().
 {
         bool rt = false;
         static uint cnt = 0;
         _curr_state = DROPPING;
         _team_name = team_name;
         for (EVER) {
                 Frequency(1);
                 switch (_curr_state) {
                         case DROPPING:
                                 rt = _do_drop();
                                 _curr_state = SEARCHING;
                         break;
                         case SEARCHING:
                                 _do_search(cnt);
                                 _curr_state = MOOVING;
                         break;
                         case MOOVING:
                                 _do_moove();
                                 _curr_state = cnt == 30 ? FORKING : SEARCHING;
                         break;
                         case FORKING:
                                 _do_fork();
                                 _curr_state = SEARCHING;
                         break;
                         case PICKING_FOOD:
                         break;
                         case PICKING_STONE:
                         break;
                 }
                 ++cnt;
                 print_state(cnt, _curr_state);
         }
         return (rt);
 }
The documentation for this class was generated from the following files:
client/ia_part/include/Trantorian.hpp
client/ia_part/src/Trantorian.cpp