PSU_zappy_2017: server/include/cmd_fcts.h File Reference
cmd_fcts.h File Reference
#include "server.h"
Functions
void * r_forward (cmdargs args, int clifd, t_world *map)
void * r_right (cmdargs args, int clifd, t_world *map)
void * r_left (cmdargs args, int clifd, t_world *map)
void * r_inventory (cmdargs args, int clifd, t_world *map)
void * r_team (cmdargs args, int clifd, t_world *map)
void * r_broadcast (cmdargs args, int clifd, t_world *map)
void * r_connect_nbr (cmdargs args, int clifd, t_world *map)
void * r_take_obj (cmdargs args, int clifd, t_world *map)
void * r_set_obj (cmdargs args, int clifd, t_world *map)
void move (t_inhabitant *player, t_world *map)
int assign_player (char *team_name, t_teams *teams, int clifd)
int count_nb_empty (t_teams *teams, char *team_name)
void * add_obj_to_player (t_inhabitant *player, char *obj_name)
int check_obj_on_map (t_world *map, int x, int y, char *obj_name)
void * del_obj_on_map (t_world *map, int x, int y, char *obj_name)
int check_obj_in_inv (t_inhabitant *player, char *obj_name)
void * del_obj_from_player (t_inhabitant *player, char *obj_name)
void * add_obj_to_map (t_world *map, int x, int y, char *obj_name)
t_inhabitant * find_player_by_fd (t_teams *teams, int clifd)
void * g_mapsize (char **args, int clifd, t_world *map)
void * g_teams_names (char **args, int clifd, t_world *map)
void * g_team_detail (char **args, int clifd, t_world *map)
Function Documentation
add_obj_to_map()
void* add_obj_to_map (t_world * map, int x, int y, char * obj_name)
Definition at line 73 of file utils2.c.
References t_ressources::deraumere, t_ressources::food, t_ressources::linemate, map, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_tile::ressources, t_ressources::sibur, t_ressources::thystame, t_world::tiles, x, and y.
Referenced by r_set_obj().
 {
         t_stone *stones[6] = {&map->tiles[x][y].ressources.sibur,
                               &map->tiles[x][y].ressources.phiras,
                               &map->tiles[x][y].ressources.mendiane,
                               &map->tiles[x][y].ressources.thystame,
                               &map->tiles[x][y].ressources.linemate,
                               &map->tiles[x][y].ressources.deraumere};
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         stones[i]->qtt += 1;
                         break;
                 }
         }
         if (strcmp(map->tiles[x][y].ressources.food.name, obj_name) == 0) {
                 map->tiles[x][y].ressources.food.qtt += 1;
         }
         return map;
 }
add_obj_to_player()
void* add_obj_to_player (t_inhabitant * player, char * obj_name)
Definition at line 74 of file utils.c.
References t_ressources::deraumere, t_ressources::food, t_inhabitant::inventory, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_ressources::sibur, and t_ressources::thystame.
Referenced by r_take_obj().
 {
         t_stone *stones[6] = {&player->inventory.sibur,
                               &player->inventory.phiras,
                               &player->inventory.mendiane,
                               &player->inventory.thystame,
                               &player->inventory.linemate,
                               &player->inventory.deraumere};
         if (strcmp(player->inventory.food.name, obj_name) == 0) {
                 player->inventory.food.qtt += 1;
         }
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         stones[i]->qtt += 1;
                         break;
                 }
         }
         return player;
 }
assign_player()
int assign_player (char * team_name, t_teams * teams, int clifd)
Definition at line 40 of file utils.c.
References t_userlist::next, and t_teams::next.
Referenced by r_team().
 {
         int exist = false;
         for (t_teams *tmpt = teams; tmpt; tmpt = tmpt->next) {
                 if (strcmp(team_name, tmpt->team_name) == 0) {
                         for (t_userlist *tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                                 if (!tmpu->user->isco) {
                                         exist = true;
                                         tmpu->user->clifd = clifd;
                                         tmpu->user->isco = true;
                                         break;
                                 }
                         }
                 }
         }
         return exist;
 }
check_obj_in_inv()
int check_obj_in_inv (t_inhabitant * player, char * obj_name)
Definition at line 30 of file utils2.c.
References t_ressources::deraumere, t_ressources::food, t_inhabitant::inventory, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_food::qtt, t_ressources::sibur, and t_ressources::thystame.
Referenced by r_set_obj().
 {
         t_stone *stones[6] = {&player->inventory.sibur,
                               &player->inventory.phiras,
                               &player->inventory.mendiane,
                               &player->inventory.thystame,
                               &player->inventory.linemate,
                               &player->inventory.deraumere};
         if (strcmp(player->inventory.food.name, obj_name) == 0) {
                 if (player->inventory.food.qtt > 0)
                         return true;
         }
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         if (stones[i]->qtt > 0)
                                 return true;
                 }
         }
         return false;
 }
check_obj_on_map()
int check_obj_on_map (t_world * map, int x, int y, char * obj_name)
Definition at line 95 of file utils.c.
References t_ressources::deraumere, t_ressources::food, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_food::qtt, t_tile::ressources, t_ressources::sibur, t_ressources::thystame, t_world::tiles, x, and y.
Referenced by r_take_obj().
 {
         t_stone *stones[6] = {&map->tiles[x][y].ressources.sibur,
                               &map->tiles[x][y].ressources.phiras,
                               &map->tiles[x][y].ressources.mendiane,
                               &map->tiles[x][y].ressources.thystame,
                               &map->tiles[x][y].ressources.linemate,
                               &map->tiles[x][y].ressources.deraumere};
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         if (stones[i]->qtt > 0)
                                 return true;
                 }
         }
         if (strcmp(map->tiles[x][y].ressources.food.name, obj_name) == 0) {
                 printf("There is food on this tile\n");
                 if (map->tiles[x][y].ressources.food.qtt > 0)
                         return true;
         }
         return false;
 }
count_nb_empty()
int count_nb_empty (t_teams * teams, char * team_name)
Definition at line 59 of file utils.c.
References t_userlist::next, and t_teams::next.
Referenced by r_connect_nbr(), and r_team().
 {
         int nb_empty = 0;
         for (t_teams *tmpt = teams; tmpt; tmpt = tmpt->next) {
                 if (strcmp(team_name, tmpt->team_name) == 0) {
                         for (t_userlist *tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                                 if (!tmpu->user->isco)
                                         nb_empty++;
                         }
                 }
         }
         return nb_empty;
 }
del_obj_from_player()
void* del_obj_from_player (t_inhabitant * player, char * obj_name)
Definition at line 52 of file utils2.c.
References t_ressources::deraumere, t_ressources::food, t_inhabitant::inventory, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_ressources::sibur, and t_ressources::thystame.
Referenced by r_set_obj().
 {
         t_stone *stones[6] = {&player->inventory.sibur,
                               &player->inventory.phiras,
                               &player->inventory.mendiane,
                               &player->inventory.thystame,
                               &player->inventory.linemate,
                               &player->inventory.deraumere};
         if (strcmp(player->inventory.food.name, obj_name) == 0) {
                 player->inventory.food.qtt -= 1;
         }
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         stones[i]->qtt -= 1;
                         break;
                 }
         }
         return player;
 }
del_obj_on_map()
void* del_obj_on_map (t_world * map, int x, int y, char * obj_name)
see send_fcts/utils2.c
Definition at line 10 of file utils2.c.
References t_ressources::deraumere, t_ressources::food, t_ressources::linemate, map, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_tile::ressources, t_ressources::sibur, t_ressources::thystame, t_world::tiles, x, and y.
Referenced by r_take_obj().
 {
         t_stone *stones[6] = {&map->tiles[x][y].ressources.sibur,
                               &map->tiles[x][y].ressources.phiras,
                               &map->tiles[x][y].ressources.mendiane,
                               &map->tiles[x][y].ressources.thystame,
                               &map->tiles[x][y].ressources.linemate,
                               &map->tiles[x][y].ressources.deraumere};
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         stones[i]->qtt -= 1;
                         break;
                 }
         }
         if (strcmp(map->tiles[x][y].ressources.food.name, obj_name) == 0) {
                 map->tiles[x][y].ressources.food.qtt -= 1;
         }
         return map;
 }
find_player_by_fd()
t_inhabitant* find_player_by_fd (t_teams * teams, int clifd)
Definition at line 11 of file find_list.c.
References t_inhabitant::clifd, t_userlist::next, t_teams::next, t_userlist::user, and t_teams::users.
Referenced by r_connect_nbr(), r_forward(), r_inventory(), r_left(), r_right(), r_set_obj(), and r_take_obj().
 {
         t_teams *tmpt;
         t_userlist *tmpu;
         for (tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (tmpu = teams->users; tmpu; tmpu = tmpu->next) {
                         if (tmpu->user->clifd == clifd)
                                 return tmpu->user;
                 }
         }
         return NULL;
 }
g_mapsize()
void* g_mapsize (char ** args, int clifd, t_world * map)
Graphical client <–> Server part
Definition at line 10 of file g_commands.c.
References t_world::sizeX, and t_world::sizeY.
 {
         if (args || !args) {
                 dprintf(clifd, "{mapsize: {x: %d, y: %d}}\n",
                 map->sizeX, map->sizeY);
         }
         return (map);
 }
g_team_detail()
void* g_team_detail (char ** args, int clifd, t_world * map)
Definition at line 43 of file g_commands.c.
References MAX_TEAM_NAME, t_teams::next, send_details(), and t_world::teams.
 {
         uint i = 0;
         for (; args[i]; ++i) {
         }
         if (i == 4 && !strcmp("team", args[2]) &&
                 strlen(args[3]) <= MAX_TEAM_NAME) {
                 for (t_teams *tmp = map->teams; tmp; tmp = tmp->next) {
                         if (strstr(args[3], tmp->team_name)) {
                                 dprintf(clifd, "{%s:{", args[3]);
                                 send_details(clifd, tmp->users);
                                 dprintf(clifd, "}}\n");
                                 break;
                         }
                 }
         }
         return (map);
 }
g_teams_names()
void* g_teams_names (char ** args, int clifd, t_world * map)
Definition at line 19 of file g_commands.c.
References t_teams::next, and t_world::teams.
 {
         dprintf(clifd, "{teamnames: [");
         if (args || !args) {
                 for (t_teams *tmp = map->teams; tmp; tmp = tmp->next) {
                         dprintf(clifd, "%s%c", tmp->team_name,
                                 tmp->next ? ',' : ']');
                 }
                 dprintf(clifd, "}\n");
         }
         return (map);
 }
move()
void move (t_inhabitant * player, t_world * map)
see send_fcts/utils.c
Definition at line 10 of file utils.c.
References t_inhabitant::curr_pos, E, N, t_inhabitant::o, S, t_world::sizeX, t_world::sizeY, and W.
Referenced by r_forward().
 {
         switch (player->o) {
         case N:
                 if (player->curr_pos[1] == (map->sizeY - 1))
                         player->curr_pos[1] -= (map->sizeY - 1);
                 else
                         player->curr_pos[1] += 1;
                 break;
         case E:
                 if (player->curr_pos[0] == (map->sizeX - 1))
                         player->curr_pos[0] -= (map->sizeX - 1);
                 else
                         player->curr_pos[0] += 1;
                 break;
         case S:
                 if (player->curr_pos[1] == (map->sizeY - 1))
                         player->curr_pos[1] += (map->sizeY - 1);
                 else
                         player->curr_pos[1] -= 1;
                 break;
         case W:
                 if (player->curr_pos[1] == (map->sizeY - 1))
                         player->curr_pos[1] -= (map->sizeY - 1);
                 else
                         player->curr_pos[0] -= 1;
                 break;
         }
 }
r_broadcast()
void* r_broadcast (cmdargs args, int clifd, t_world * map)
Definition at line 25 of file broadcast.c.
References t_world::graphical_fd, map, t_userlist::next, t_teams::next, and t_world::teams.
 {
         if (!args[1])
                 return map;
         for (t_teams *tmpt = map->teams; tmpt; tmpt = tmpt->next) {
                 for (t_userlist *tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                         if (tmpu->user->clifd != clifd && tmpu->user->isco) {
                                 dprintf(tmpu->user->clifd, "%s\n", args[1]);
                                 dprintf(map->graphical_fd ,"pbc %d %s\n",
                                         tmpu->user->clifd, args[1]);
                         }
                 }
         }
         return map;
 }
r_connect_nbr()
void* r_connect_nbr (cmdargs args, int clifd, t_world * map)
Definition at line 41 of file broadcast.c.
References count_nb_empty(), find_player_by_fd(), map, t_inhabitant::team_name, and t_world::teams.
 {
         args[0][0] = 'c';
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         dprintf(clifd, "%d\n", count_nb_empty(map->teams, player->team_name));
         return map;
 }
r_forward()
void* r_forward (cmdargs args, int clifd, t_world * map)
IA <–> Server part see send_fcts/motion.c
Definition at line 11 of file motion.c.
References find_player_by_fd(), map, move(), and t_world::teams.
 {
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         args[0][0] = 'c';
         move(player, map);
         dprintf(clifd, "ok\n");
         return map;
 }
r_inventory()
void* r_inventory (cmdargs args, int clifd, t_world * map)
Definition at line 69 of file motion.c.
References t_ressources::deraumere, find_player_by_fd(), t_ressources::food, t_inhabitant::inventory, t_ressources::linemate, map, t_ressources::mendiane, t_stone::name, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_ressources::sibur, t_world::teams, and t_ressources::thystame.
 {
         args[0][0] = 'c';
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         dprintf(clifd,
                 "[%s %d, %s %d, %s %d, %s %d, %s %d, %s %d, %s %d]\n",
                 player->inventory.food.name,
                 player->inventory.food.qtt,
                 player->inventory.linemate.name,
                 player->inventory.linemate.qtt,
                 player->inventory.deraumere.name,
                 player->inventory.deraumere.qtt,
                 player->inventory.sibur.name,
                 player->inventory.sibur.qtt,
                 player->inventory.mendiane.name,
                 player->inventory.mendiane.qtt,
                 player->inventory.phiras.name,
                 player->inventory.phiras.qtt,
                 player->inventory.thystame.name,
                 player->inventory.thystame.qtt);
         return map;
 }
r_left()
void* r_left (cmdargs args, int clifd, t_world * map)
Definition at line 45 of file motion.c.
References E, find_player_by_fd(), map, N, t_inhabitant::o, S, t_world::teams, and W.
 {
         args[0][0] = 'c';
         printf("turn left\n");
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         switch (player->o) {
         case N:
                 player->o = W;
                 break;
         case E:
                 player->o = N;
                 break;
         case S:
                 player->o = E;
                 break;
         case W:
                 player->o = S;
                 break;
         }
         dprintf(clifd, "ok\n");
         return map;
 }
r_right()
void* r_right (cmdargs args, int clifd, t_world * map)
Definition at line 21 of file motion.c.
References E, find_player_by_fd(), map, N, t_inhabitant::o, S, t_world::teams, and W.
 {
         args[0][0] = 'c';
         printf("turn right\n");
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         switch (player->o) {
         case N:
                 player->o = E;
                 break;
         case E:
                 player->o = S;
                 break;
         case S:
                 player->o = W;
                 break;
         case W:
                 player->o = N;
                 break;
         }
         dprintf(clifd, "ok\n");
         return map;
 }
r_set_obj()
void* r_set_obj (cmdargs args, int clifd, t_world * map)
Definition at line 71 of file broadcast.c.
References add_obj_to_map(), check_obj_in_inv(), t_inhabitant::curr_pos, del_obj_from_player(), find_player_by_fd(), t_ressources::food, t_inhabitant::inventory, map, t_food::qtt, t_tile::ressources, t_world::teams, t_world::tiles, x, and y.
 {
         args[0][0] = 'c';
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         int x = player->curr_pos[0];
         int y = player->curr_pos[1];
         printf("Player's food before:\t%d\n", player->inventory.food.qtt);
         printf("Food on tile before:\t%d\n", map->tiles[x][y].ressources.food.qtt);
         if (check_obj_in_inv(player, args[1])) {
                 player = del_obj_from_player(player, args[1]);
                 add_obj_to_map(map, x, y, args[1]);
                 dprintf(clifd, "ok\n");
         }
         else
                 dprintf(clifd, "ko\n");
         printf("Player's food after:\t%d\n", player->inventory.food.qtt);
         printf("Food on tile after:\t%d\n", map->tiles[x][y].ressources.food.qtt);
         return map;
 }
r_take_obj()
void* r_take_obj (cmdargs args, int clifd, t_world * map)
Definition at line 50 of file broadcast.c.
References add_obj_to_player(), check_obj_on_map(), t_inhabitant::curr_pos, del_obj_on_map(), find_player_by_fd(), t_ressources::food, t_inhabitant::inventory, map, t_food::qtt, t_tile::ressources, t_world::teams, t_world::tiles, x, and y.
 {
         args[0][0] = 'c';
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         int x = player->curr_pos[0];
         int y = player->curr_pos[1];
         printf("Player's food before:\t%d\n", player->inventory.food.qtt);
         printf("Food on tile before:\t%d\n", map->tiles[x][y].ressources.food.qtt);
         if (check_obj_on_map(map, x, y, args[1])) {
                 player = add_obj_to_player(player, args[1]);
                 del_obj_on_map(map, x, y, args[1]);
                 dprintf(clifd, "ok\n");
         }
         else
                 dprintf(clifd, "ko\n");
         printf("Player's food after:\t%d\n", player->inventory.food.qtt);
         printf("Food on tile after:\t%d\n", map->tiles[x][y].ressources.food.qtt);
         return map;
 }
r_team()
void* r_team (cmdargs args, int clifd, t_world * map)
see send_fcts/broadcast.c
Definition at line 10 of file broadcast.c.
References assign_player(), count_nb_empty(), t_world::graphical_fd, map, t_world::sizeX, t_world::sizeY, and t_world::teams.
 {
         if (args[1] && strcmp(args[1], "graphical") == 0) {
                 map->graphical_fd = clifd;
                 dprintf(clifd, "GRAPHICAL SOCKET\n");
         } else if (args[1] && assign_player(args[1], map->teams, clifd)) {
                 dprintf(clifd, "%d\n%d %d\n",
                         count_nb_empty(map->teams, args[1]),
                         map->sizeX, map->sizeY);
         } else {
                 dprintf(clifd, "ko\n");
         }
         return map;
 }