PSU_zappy_2017: server_src/send_fcts/cmd.c File Reference
cmd.c File Reference
#include "cmd_fcts.h"
Functions
void * send_res_drop (cmdargs args, int clifd, t_teams *teams)
void * send_res_collect (cmdargs args, int clifd, t_teams *teams)
void * send_msg (cmdargs args, int clifd, t_teams *teams)
void * send_cmd_unknow (cmdargs args, int clifd, t_teams *teams)
void * send_cmd_params (cmdargs args, int clifd, t_teams *teams)
Function Documentation
send_cmd_params()
void* send_cmd_params (cmdargs args, int clifd, t_teams * teams)
Definition at line 54 of file cmd.c.
 {
         dprintf(clifd, "sbp\n");
 }
send_cmd_unknow()
void* send_cmd_unknow (cmdargs args, int clifd, t_teams * teams)
Definition at line 49 of file cmd.c.
 {
         dprintf(clifd, "suc\n");
 }
send_msg()
void* send_msg (cmdargs args, int clifd, t_teams * teams)
Definition at line 38 of file cmd.c.
References t_userlist::next, t_teams::next, and teams.
 {
         for (t_teams *tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (t_userlist *tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                         dprintf(tmpu->user->clifd, "smg %s\n", args[0]);
                 }
         }
         return teams;
 }
send_res_collect()
void* send_res_collect (cmdargs args, int clifd, t_teams * teams)
Definition at line 24 of file cmd.c.
References find_user_in_teams(), t_userlist::next, t_teams::next, teams, and user().
 {
         t_user *user = find_user_in_teams(teams, clifd);
         for (t_teams tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (t_userlist tmpu = tmpu->users; tmpu; tmpu = tmpu->next) {
                         dprintf(tmpu->user->clifd, "pgt %d %d\n",
                                 tmpu->user->refplayer->id,
                                 tmpu->user->refplayer->just_collect);
                 }
         }
         return teams;
 }
send_res_drop()
void* send_res_drop (cmdargs args, int clifd, t_teams * teams)
Definition at line 10 of file cmd.c.
References find_user_in_teams(), t_userlist::next, t_teams::next, teams, and user().
 {
         t_user *user = find_user_in_teams(teams, clifd);
         for (t_teams tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (t_userlist tmpu = tmpu->users; tmpu; tmpu = tmpu->next) {
                         dprintf(tmpu->user->clifd, "pdr %d %d\n",
                                 tmpu->user->refplayer->id,
                                 tmpu->user->refplayer->just_drop);
                 }
         }
         return teams;
 }