PSU_zappy_2017: server/src/commands_parsing.c File Reference
commands_parsing.c File Reference
#include "../include/server.h"
#include <stdlib.h>
Functions
static char ** get_commands (char *req)
static char ** get_args (char *cmd)
int get_methods (char *req, int clifd, t_world *map)
Function Documentation
get_args()
static char** get_args (char * cmd) static
Tokenize the command buffer by splitting by spaces
Parameters
cmd a command string received after get_commands() tokenization
Definition at line 36 of file commands_parsing.c.
References MAXARGS.
Referenced by get_methods().
 {
         int i = 0;
         char *token = NULL;
         char **tkns = malloc(MAXARGS * sizeof(*tkns));
         if (tkns) {
                 memset(tkns, 0, sizeof(*tkns) * MAXARGS);
                 token = strtok(cmd, " :");
                 while (token) {
                         tkns[i] = strdup(token);
                         token = strtok(NULL, " :");
                         i = i <= MAXARGS ? i + 1 : i;
                 }
         }
         return (tkns);
 }
get_commands()
static char** get_commands (char * req) static
Split the received buffer by the '\r\n' symbol to get multiple commands in one buffer (or only one it's all depends on the client)
Parameters
req the read() buffer from clifd
Definition at line 15 of file commands_parsing.c.
References MAXARGS.
Referenced by get_methods().
 {
         int i = 0;
         char *cmd = NULL;
         char **cmds = malloc(MAXARGS * sizeof(*cmds));
         if (cmds) {
                 memset(cmds, 0, sizeof(*cmds) * MAXARGS);
                 cmd = strtok(req, "\r\n");
                 while (cmd) {
                         cmds[i] = strdup(cmd);
                         cmd = strtok(NULL, "\r\n");
                         i = i <= MAXARGS ? i + 1 : i;
                 }
         }
         return (cmds);
 }
get_methods()
int get_methods (char * req, int clifd, t_world * map)
Match all methods in G_CMDS for a given req command string
Parameters
req the readed commands buffer
clifd the client socket fd
Note
could add compilation macro for debug print_2darray() calls but epitech norm insist on 20 line per function so ...
Definition at line 60 of file commands_parsing.c.
References free_buffers(), G_CMDS, G_PROTOS, get_args(), get_commands(), and REF_NB.
Referenced by events_handler().
 {
         printf("get_methods: %s\n", req);
         int index = 0;
         char **cmds = get_commands(req);
         char **args = NULL;
 //      static t_teams *defchan = NULL;
 //      defchan = !defchan ? init_default_teams() : defchan;
         for (int j = 0; cmds[j]; ++j) {
                 for (index = 0; G_PROTOS[index]; ++index) {
                         if ((strstr(cmds[j], G_PROTOS[index]))) {
                                 args = get_args(cmds[j]);
                                 G_CMDS[index](args, clifd, map);
                                 free_buffers(args);
                                 break;
                         }
                 }
         }
 //      print_users_in_chans(defchan, index);
         free_buffers(cmds);
         return ((index == REF_NB) ? (0) : (index));
 }