PSU_zappy_2017: server_src/send_fcts/find_list.c File Reference
find_list.c File Reference
#include "cmd_fcts.h"
Functions
t_user * find_user_in_teams (t_teams *teams, int clifd)
t_user * find_player_by_id (t_teams *teams, unsigned int id)
int get_nbr_by_level (int level)
t_egg * find_egg_on_tile (t_tile *tile, t_user *layer)
t_egg * find_egg_state (t_user *user, EGG_STATE state)
Function Documentation
find_egg_on_tile()
t_egg* find_egg_on_tile (t_tile * tile, t_user * layer)
Definition at line 58 of file find_list.c.
References t_tile::eggs, t_egg::id_droper, and t_egg::next.
 {
         t_egg *tmpe;
         for (tmpe = tile->eggs; tmpe; tmpe = tmpe->next) {
                 if (tmpe->id_droper == layer->refplayer->id)
                         break;
         }
         return tmpe;
 }
find_egg_state()
t_egg* find_egg_state (t_user * user, EGG_STATE state)
Definition at line 70 of file find_list.c.
References DEAD, t_egg::ev, HATCHED, and t_egg::next.
Referenced by send_egg_death(), and send_egg_hatch().
 {
         t_egg *tmpe;
         for (tmpe = user->refplayer->eggs; tmpe; tmpe = tmpe->next) {
                 if (tmpe->ev == HATCHED && state == HATCHED)
                         break;
                 if (tmpe->ev == DEAD && state == DEAD)
                         break;
         }
         return tmpe;
 }
find_player_by_id()
t_user* find_player_by_id (t_teams * teams, unsigned int id)
Definition at line 24 of file find_list.c.
References t_inhabitant::id, t_userlist::next, t_teams::next, t_userlist::user, and t_teams::users.
Referenced by send_player_inv(), and send_player_lv().
 {
         t_teams *tmpt;
         t_userlist *tmpu;
         for (tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (tmpu = teams->users; tmpu; tmpu = tmpu->next) {
                         if (tmpu->user->refplayer->id == id)
                                 return tmpu->user;
                 }
         }
         return NULL;
 }
find_user_in_teams()
t_user* find_user_in_teams (t_teams * teams, int clifd)
Definition at line 10 of file find_list.c.
References t_inhabitant::clifd, t_userlist::next, t_teams::next, t_userlist::user, and t_teams::users.
Referenced by send_broadcast(), send_egg_death(), send_egg_hatch(), send_expulsion(), send_inc_end(), send_inc_start(), send_player_pos(), send_res_collect(), and send_res_drop().
 {
         t_teams *tmpt;
         t_userlist *tmpu;
         for (tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (tmpu = teams->users; tmpu; tmpu = tmpu->next) {
                         if (tmpu->user->clifd == clifd)
                                 return tmpu->user;
                 }
         }
         return NULL;
 }
get_nbr_by_level()
int get_nbr_by_level (int level)
Definition at line 38 of file find_list.c.
Referenced by send_inc_start().
 {
         int nbr;
         if (level == 1)
                 nbr = 1;
         else if (level == 2 || level == 3)
                 nbr = 2;
         else if (level == 4 || level == 5)
                 nbr = 4;
         else if (level == 6 || level == 7)
                 nbr = 6;
         else
                 nbr = 0;
         return nbr;
 }