PSU_zappy_2017: server/src/send_fcts/g_commands.c File Reference
g_commands.c File Reference
#include <unistd.h>
#include "../../include/cmd_fcts.h"
Functions
void * g_mapsize (char **args, int clifd, t_world *map)
void * g_teams_names (char **args, int clifd, t_world *map)
void send_details (int clifd, t_userlist *teams_members)
void * g_team_detail (char **args, int clifd, t_world *map)
Function Documentation
g_mapsize()
void* g_mapsize (char ** args, int clifd, t_world * map)
The GET /mapsize route implementation
Parameters
args the unusued mapsize command arguments
clifd the unique client socket file descriptor
map the t_world::map for Trantor world
Note
With curl request :
open a shell, install curl and jq (json pretty printer)
in another shell launch ./zappy_server with required args
in curl shell, launch curl -s -X GET http://127.0.0.1:2222/mapsize | jq
Definition at line 20 of file g_commands.c.
References t_world::sizeX, and t_world::sizeY.
 {
         if (args || !args) {
                 dprintf(clifd, "{\"mapsize\": {\"x\": %d, \"y\": %d} }\n",
                 map->sizeX, map->sizeY);
         }
         close(clifd);
         return (map);
 }
g_team_detail()
void* g_team_detail (char ** args, int clifd, t_world * map)
The POST /team_detail&team= route implementation
Parameters
args the requested team to look
clifd the unique client socket file descriptor
map the t_world::map for Trantor world
Note
With curl request :
open a shell, install curl and jq (json pretty printer)
in another shell launch ./zappy_server with required args
in curl shell, launch curl -s -X POST http://127.0.0.1:2222/team_detail&team=XX | jq
Definition at line 79 of file g_commands.c.
References get_size(), MAX_TEAM_NAME, t_teams::next, send_details(), and t_world::teams.
 {
         uint i = get_size(args);
         if (i >= 4 && !strcmp("team", args[2]) &&
                 strlen(args[3]) <= MAX_TEAM_NAME) {
                 for (t_teams *tmp = map->teams; tmp; tmp = tmp->next) {
                         if (strstr(args[3], tmp->team_name)) {
                                 dprintf(clifd, "{\"%s\":[", args[3]);
                                 send_details(clifd, tmp->users);
                                 dprintf(clifd, "]}\n");
                                 break;
                         }
                 }
         }
         close(clifd);
         return (map);
 }
g_teams_names()
void* g_teams_names (char ** args, int clifd, t_world * map)
The GET /teamnames route implementation
Parameters
args the unusued mapsize command arguments
clifd the unique client socket file descriptor
map the t_world::map for Trantor world
Note
With curl request :
open a shell, install curl and jq (json pretty printer)
in another shell launch ./zappy_server with required args
in curl shell, launch curl -s -X GET http://127.0.0.1:2222/teamnames | jq
Definition at line 39 of file g_commands.c.
References t_teams::next, and t_world::teams.
 {
         dprintf(clifd, "{\"teamnames\": [");
         if (args || !args) {
                 for (t_teams *tmp = map->teams; tmp; tmp = tmp->next) {
                         dprintf(clifd, "\"%s\"%s", tmp->team_name,
                                 tmp->next ? ", " : "]");
                 }
                 dprintf(clifd, "}\n");
         }
         close(clifd);
         return (map);
 }
send_details()
void send_details (int clifd, t_userlist * teams_members)
Util function to send teams content
Parameters
clifd the client socket for writing response
teams_members the teams linked list
Definition at line 57 of file g_commands.c.
References t_userlist::next, X, and Y.
Referenced by g_team_detail().
 {
         uint id = 0;
         for (t_userlist *tmp = teams_members; tmp; tmp = tmp->next) {
                 dprintf(clifd, "{\"id\": %d , \"x\": %d , ",
                 id, tmp->user->curr_pos[X]);
                 dprintf(clifd, "\"y\":%d , \"ttl\": %0.3f}%s",
                 tmp->user->curr_pos[Y], tmp->user->ttl,
                 tmp->next ? ", " : "\n");
         }
 }