PSU_zappy_2017Server: server_src/lists_finders.c File Reference
lists_finders.c File Reference
#include "../include/server.h"
#include <stdlib.h>
Functions
unsigned int get_size (cmdargs args)
t_user * find_user_by_fd (t_userlist *list, int clifd)
t_teams * get_team_by_name (t_teams *list, char *channame)
unsigned int is_user_in_chan (int clifd, t_teams *chans)
t_user * find_user_by_name (const char *name, t_userlist *usrs)
Function Documentation
find_user_by_fd()
t_user* find_user_by_fd (t_userlist * list, int clifd)
Find a t_user structure pointer if clientfd exist inside
Parameters
list the full userlist
clifd the 'to find' client fd
Returns
user if clientfd exist in the list
NULL pointer if nothing found
Definition at line 30 of file lists_finders.c.
References t_userlist::next.
Referenced by join(), privmsg(), and quit().
 {
         t_user *usr = NULL;
         for (t_userlist *tmp = list; tmp; tmp = tmp->next) {
                 if (tmp->user->clifd == clifd) {
                         usr = tmp->user;
                         break;
                 }
         }
         return (usr);
 }
find_user_by_name()
t_user* find_user_by_name (const char * name, t_userlist * usrs)
Find a user by name literaly
Parameters
name the name to find
Definition at line 76 of file lists_finders.c.
References t_userlist::next.
Referenced by privmsg().
 {
         t_user *needle = NULL;
         for (t_userlist *foo = usrs; foo; foo = foo->next) {
                 if (!strcmp(name, foo->user->nick) ||
                 !strcmp(name, foo->user->rname)) {
                         needle = foo->user;
                         break;
                 }
         }
         return (needle);
 }
get_size()
unsigned int get_size (cmdargs args)
Get the size of a 2d Array
Returns
i the size of the cmdargs 2d char *array
Definition at line 14 of file lists_finders.c.
Referenced by user().
 {
         unsigned int i = 0;
         while (args[i]) {
                 ++i;
         }
         return (i);
 }
get_team_by_name()
t_teams* get_team_by_name (t_teams * list, char * channame)
Get the t_teams pointer by its name
Parameters
list the teams list
channame the resquested teams
Returns
a t_teams pointer if exists , NULL otherwise
Definition at line 48 of file lists_finders.c.
References t_teams::next.
Referenced by join(), and privmsg().
 {
         t_teams *rt = NULL;
         for (t_teams *tmp = list; tmp; tmp = tmp->next) {
                 if (!strcmp(tmp->channame, channame)) {
                         rt = tmp;
                         break;
                 }
         }
         return (rt);
 }
is_user_in_chan()
unsigned int is_user_in_chan (int clifd, t_teams * chans)
Definition at line 61 of file lists_finders.c.
References t_teams::channame, t_userlist::next, and t_teams::users.
Referenced by quit().
 {
         for (t_userlist *usrs = chans->users; usrs; usrs = usrs->next) {
                 if (clifd == usrs->user->clifd) {
                         printf("Chan name [%s] Is in list ? [%s]\n",
                         chans->channame, usrs->user->nick);
                         usrs->user->isco = false;
                 }
         }
         return (1);
 }