BrokenIRC: server_src/lists_helpers.c File Reference
lists_helpers.c File Reference
#include "../include/server.h"
Functions
t_user * find_user_by_fd (t_userlist *list, int clifd)
t_channel * get_chan_by_name (t_channel *list, char *channame)
Function Documentation
find_user_by_fd()
t_user* find_user_by_fd (t_userlist * list, int clifd)
Find a t_user structure pointer if clientfd exist inside
Parameters
list the full userlist
clifd the 'to find' client fd
Returns
user if clientfd exist in the list
NULL pointer if nothing found
Definition at line 16 of file lists_helpers.c.
References t_userlist::next.
Referenced by join(), privmsg(), and quit().
 {
         t_user *usr = NULL;
         for (t_userlist *tmp = list; tmp; tmp = tmp->next) {
                 if (tmp->user->clifd == clifd) {
                         usr = tmp->user;
                         break;
                 }
         }
         return (usr);
 }
get_chan_by_name()
t_channel* get_chan_by_name (t_channel * list, char * channame)
Get the t_channel pointer by its name
Parameters
list the channel list
channame the resquested channel
Returns
a t_channel pointer if exists , NULL otherwise
Definition at line 34 of file lists_helpers.c.
References t_channel::next.
Referenced by join(), and privmsg().
 {
         t_channel *rt = NULL;
         for (t_channel *tmp = list; tmp; tmp = tmp->next) {
                 if (!strcmp(tmp->channame, channame)) {
                         rt = tmp;
                         break;
                 }
         }
         return (rt);
 }