BrokenIRC: server_src/logs_helpers.c File Reference
logs_helpers.c File Reference
#include "../include/server.h"
#include <unistd.h>
#include <stdlib.h>
Functions
void print_users_in_chans (t_channel *chanlist, int index)
void print_users (t_userlist *list)
static char * get_host_string (const char *host, const char *service)
int logthisevent (const char etype, t_serv *all)
Function Documentation
get_host_string()
static char* get_host_string (const char * host, const char * service) static
Construct the host:service string from struct infos
Note
this is to avoid sprintf usage
Definition at line 43 of file logs_helpers.c.
Referenced by logthisevent().
 {
         char *usr = malloc((NI_MAXHOST + 1 + NI_MAXSERV) * sizeof(*usr));
         memset(usr, 0, NI_MAXHOST + 1 + NI_MAXSERV);
         strncpy(usr, host, NI_MAXHOST);
         strcat(usr, ":");
         strncat(usr, service, NI_MAXSERV);
         return (usr);
 }
logthisevent()
int logthisevent (const char etype, t_serv * all)
Switch type and print data in t_serv according to a fmt string
Parameters
etype the kind of event type in [C]onnect, [D]isconnect or default
all the 'catch them all' structure with server infos
Returns
1
Definition at line 59 of file logs_helpers.c.
References t_serv::buf, get_host_string(), t_serv::host, t_serv::nread, and t_serv::service.
Referenced by evhandler().
 {
         char *usr = get_host_string(all->host, all->service);
         char *c_fmt = " => IN: [%zd bytes] FROM: [%s] DATA: [%s]\n";
         char *d_fmt = "USER: [%s] disconnect\n";
         char *def_fmt = "Type:%c Size:%zd DATA: [%s]\n";
         switch (etype) {
                 case 'c':
                         fprintf(stdout, c_fmt, all->nread, usr, all->buf);
                         break;
                 case 'd':
                         fprintf(stdout, d_fmt, usr);
                         break;
                 default:
                         fprintf(stdout, def_fmt, etype, all->nread, all->buf);
                         break;
         }
         free(usr);
         return (1);
 }
print_users()
void print_users (t_userlist * list)
Print users nick and real name stored in a t_userlist doubly linked list
Parameters
liste the t_userlist to print
Definition at line 30 of file logs_helpers.c.
References t_userlist::next.
Referenced by print_users_in_chans().
 {
         printf("\t\tUSERS LIST :\n");
         for (t_userlist *tmp = list; tmp; tmp = tmp->next) {
                 printf("User : [%s], Real Name : [%s]\n",
                 tmp->user->nick, tmp->user->rname);
         }
         printf("\n");
 }
print_users_in_chans()
void print_users_in_chans (t_channel * chanlist, int index)
Print each channel in list with its users
Parameters
chanlist the channels doubly linked list
index the received command index to avoid printing each time a PING cmd is received (too much log ;))
Definition at line 17 of file logs_helpers.c.
References t_channel::next, PING, and print_users().
Referenced by get_methods().
 {
         if (index != PING) {
                 for (t_channel *tmp = chanlist; tmp; tmp = tmp->next) {
                         printf("\tChannel : [%s]\n", tmp->channame);
                         print_users(tmp->users);
                 }
         }
 }