PSU_zappy_2017: client/ia_part/src/main.cpp File Reference
main.cpp File Reference
#include "../include/Trantorian.hpp"
Functions
void usage (const char *progname)
std::map< std::string, std::string > get_opts (char **av)
bool check_opts (std::map< std::string, std::string > opts)
int main (int ac, char **av)
Function Documentation
check_opts()
bool check_opts (std::map< std::string, std::string > opts)
Check if all required flags are provided
Parameters
opts the map of flags and their values
Returns
rt true if correct args, false otherwise
Definition at line 39 of file main.cpp.
References true.
Referenced by main().
 {
         bool rt = opts.find("-p") != opts.end()
         && opts.find("-n") != opts.end()
         && opts.find("-h") != opts.end() ? true : false;
         if (rt) {
                 int port  = std::stoi(opts["-p"]);
                 std::string team_name = opts["-n"];
                 std::string server_host = opts["-h"];
                 rt = port >= 1024 ? true : rt;
         }
         return (rt);
 }
get_opts()
std::map<std::string, std::string> get_opts (char ** av)
Turn the 2D argv array to a key , value pairs map
Parameters
av the argv array from main()
Returns
map a string key and string value map
Definition at line 26 of file main.cpp.
References map.
Referenced by main().
 {
         std::map<std::string, std::string> map;
         for (uint i = 1; av[i]; ++i) {
                 map[av[i]] = av[i + 1] ? av[i + 1] : "";
         }
         return (map);
 }
main()
int main (int ac, char ** av)
The zappy_ai main entry point, check the args and run
Parameters
ac the number of av args
av the arguments like -[flag] [value]
Definition at line 58 of file main.cpp.
References Trantorian::check_co(), check_opts(), get_opts(), Trantorian::run(), and usage().
 {
         int rt = 84;
         if (ac >= 4) {
                 std::map<std::string, std::string> opts = get_opts(av);
                 bool check = check_opts(opts);
                 if (check) {
                         Trantorian ia_player(opts["-p"], opts["-h"]);
                         check = ia_player.check_co();
                         if (check) {
                                 ia_player.run(opts["-n"]);
                         }
                         rt = 0;
                 } else {
                         opts.clear();
                         usage(av[0]);
                 }
         } else
                 usage(av[0]);
         return (rt);
 }
usage()
void usage (const char * progname)
Dummy print usage function
Parameters
progname the programm name
Definition at line 13 of file main.cpp.
Referenced by main().
 {
         std::cerr << "USAGE: " << progname << " -p port -n name -h machine\n";
         std::cerr << "\tport\tis the port number\n";
         std::cerr << "\tname\tis the name of the team\n";
         std::cerr << "\tmachine\tis the name of the machine;";
         std::cerr << " localhost by default\n";
 }