PSU_zappy_2017: server/src/send_fcts/motion.c File Reference
motion.c File Reference
#include "cmd_fcts.h"
Functions
void * r_forward (cmdargs args, int clifd, t_world *map)
void * r_right (cmdargs args, int clifd, t_world *map)
void * r_left (cmdargs args, int clifd, t_world *map)
void * r_inventory (cmdargs args, int clifd, t_world *map)
Function Documentation
r_forward()
void* r_forward (cmdargs args, int clifd, t_world * map)
IA <–> Server part see send_fcts/motion.c
Definition at line 11 of file motion.c.
References find_player_by_fd(), map, move(), and t_world::teams.
 {
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         args[0][0] = 'c';
         move(player, map);
         dprintf(clifd, "ok\n");
         return map;
 }
r_inventory()
void* r_inventory (cmdargs args, int clifd, t_world * map)
Definition at line 69 of file motion.c.
References t_ressources::deraumere, find_player_by_fd(), t_ressources::food, t_inhabitant::inventory, t_ressources::linemate, map, t_ressources::mendiane, t_stone::name, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_ressources::sibur, t_world::teams, and t_ressources::thystame.
 {
         args[0][0] = 'c';
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         dprintf(clifd,
                 "[%s %d, %s %d, %s %d, %s %d, %s %d, %s %d, %s %d]\n",
                 player->inventory.food.name,
                 player->inventory.food.qtt,
                 player->inventory.linemate.name,
                 player->inventory.linemate.qtt,
                 player->inventory.deraumere.name,
                 player->inventory.deraumere.qtt,
                 player->inventory.sibur.name,
                 player->inventory.sibur.qtt,
                 player->inventory.mendiane.name,
                 player->inventory.mendiane.qtt,
                 player->inventory.phiras.name,
                 player->inventory.phiras.qtt,
                 player->inventory.thystame.name,
                 player->inventory.thystame.qtt);
         return map;
 }
r_left()
void* r_left (cmdargs args, int clifd, t_world * map)
Definition at line 45 of file motion.c.
References E, find_player_by_fd(), map, N, t_inhabitant::o, S, t_world::teams, and W.
 {
         args[0][0] = 'c';
         printf("turn left\n");
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         switch (player->o) {
         case N:
                 player->o = W;
                 break;
         case E:
                 player->o = N;
                 break;
         case S:
                 player->o = E;
                 break;
         case W:
                 player->o = S;
                 break;
         }
         dprintf(clifd, "ok\n");
         return map;
 }
r_right()
void* r_right (cmdargs args, int clifd, t_world * map)
Definition at line 21 of file motion.c.
References E, find_player_by_fd(), map, N, t_inhabitant::o, S, t_world::teams, and W.
 {
         args[0][0] = 'c';
         printf("turn right\n");
         t_inhabitant *player = find_player_by_fd(map->teams, clifd);
         switch (player->o) {
         case N:
                 player->o = E;
                 break;
         case E:
                 player->o = S;
                 break;
         case S:
                 player->o = W;
                 break;
         case W:
                 player->o = N;
                 break;
         }
         dprintf(clifd, "ok\n");
         return map;
 }