PSU_zappy_2017: server_src/send_fcts/player.c File Reference
player.c File Reference
#include "cmd_fcts.h"
Functions
void * send_player_join (cmdargs args, int clifd, t_teams *teams)
void * send_player_pos (cmdargs args, int clifd, t_teams *teams)
void * send_player_lv (cmdargs args, int clifd, t_teams *teams)
void * send_player_inv (cmdargs args, int clifd, t_teams *teams)
void * send_player_death (cmdargs args, int clifd, t_teams *teams)
Function Documentation
send_player_death()
void* send_player_death (cmdargs args, int clifd, t_teams * teams)
Definition at line 72 of file player.c.
References t_inhabitant::clifd, t_userlist::next, t_teams::next, teams, t_userlist::user, and t_teams::users.
 {
         t_user *playern = find_user_in_team(teams, clifd);
         t_teams *tmpt;
         t_userlist *tmpu;
         for (tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                         dprintf(tmpu->user->clifd, "pdi %d\n",
                                 playern->refplayer->id);
                 }
         }
         return teams;
 }
send_player_inv()
void* send_player_inv (cmdargs args, int clifd, t_teams * teams)
Definition at line 53 of file player.c.
References find_player_by_id(), and teams.
 {
         int n = atoi(args[0]);
         t_user *playern = find_player_by_id(teams, n);
         dprintf(clifd, "pin %d %d %d %d %d %d %d %d %d %d\n", n,
                 playern->refplayer->curr_pos[0],
                 playern->refplayer->curr_pos[1],
                 playern->refplayer->inventory.food.qtt,
                 playern->refplayer->inventory.linemate.qtt,
                 playern->refplayer->inventory.deraumere.qtt,
                 playern->refplayer->inventory.sibur.qtt,
                 playern->refplayer->inventory.mendiane.qtt,
                 playern->refplayer->inventory.phiras.qtt,
                 playern->refplayer->inventory.thystame.qtt);
         return teams;
 }
send_player_join()
void* send_player_join (cmdargs args, int clifd, t_teams * teams)
Definition at line 10 of file player.c.
References t_inhabitant::clifd, t_inhabitant::curr_pos, t_inhabitant::id, t_inhabitant::level, t_userlist::next, t_teams::next, t_inhabitant::o, t_teams::team_name, teams, t_userlist::user, and t_teams::users.
 {
         t_teams *tmpt;
         t_userlist *tmpu;
         for (tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                         dprintf(tmpu->user->clifd, "pnw %d %d %d %d %d %d\n",
                                 tmpu->user->refplayer->id,
                                 tmpu->user->refplayer->curr_pos[0],
                                 tmpu->user->refplayer->curr_pos[1],
                                 tmpu->user->refplayer->o,
                                 tmpu->user->refplayer->level,
                                 tmpt->team_name);
                 }
         }
         return teams;
 }
send_player_lv()
void* send_player_lv (cmdargs args, int clifd, t_teams * teams)
Definition at line 43 of file player.c.
References find_player_by_id(), and teams.
 {
         int n = atoi(args[0]);
         t_user *playern = find_player_by_id(teams, n);
         dprintf(clifd, "plv %d %d\n", n, playern->refplayer->level);
         return teams;
 }
send_player_pos()
void* send_player_pos (cmdargs args, int clifd, t_teams * teams)
Definition at line 29 of file player.c.
References find_user_in_teams(), and teams.
 {
         t_user *sender;
         if ((sender = find_user_in_teams(teams, clifd))) {
                 dprintf(clifd, "ppo %d %d %d %d\n",
                         sender->refplayer->id,
                         sender->refplayer->curr_por[0],
                         sender->refplayer->curr_por[1],
                         sender->refplayer->o);
         }
         return teams;
 }