PSU_zappy_2017: server/src/varioushelpers_functions/print_items.c File Reference
print_items.c File Reference
#include "server.h"
Functions
uint get_size (char **args)
void print_world (t_world *map)
void print_teams (t_teams *teams)
Function Documentation
get_size()
uint get_size (char ** args)
Definition at line 10 of file print_items.c.
Referenced by g_team_detail().
 {
         uint size = 0;
         while (args[size]) {
                 ++size;
         }
         return (size);
 }
print_teams()
void print_teams (t_teams * teams)
Definition at line 31 of file print_items.c.
References t_userlist::next, and t_teams::next.
Referenced by server().
 {
         for (t_teams *tmpt = teams; tmpt; tmpt = tmpt->next) {
                 printf("%s\n", tmpt->team_name);
                 for (t_userlist *tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                         printf("%d[%s]: X=%d Y=%d %d %d %d %d %d %d %d ttl:%f\n",
                                tmpu->user->id, tmpu->user->team_name,
                                tmpu->user->curr_pos[0], tmpu->user->curr_pos[1],
                                tmpu->user->inventory.food.qtt,
                                tmpu->user->inventory.linemate.qtt,
                                tmpu->user->inventory.deraumere.qtt,
                                tmpu->user->inventory.sibur.qtt,
                                tmpu->user->inventory.mendiane.qtt,
                                tmpu->user->inventory.phiras.qtt,
                                tmpu->user->inventory.thystame.qtt,
                                tmpu->user->ttl);
                 }
                 printf("\n");
         }
 }
print_world()
void print_world (t_world * map)
Note
Print objects see src/print_fcts.c
Definition at line 20 of file print_items.c.
References t_ressources::food, t_food::qtt, t_tile::ressources, t_world::sizeX, t_world::sizeY, and t_world::tiles.
Referenced by server().
 {
         for (int i = 0; i < map->sizeX; i++) {
                 for (int j = 0; j < map->sizeY; j++) {
                         printf("%d ", map->tiles[i][j].ressources.food.qtt);
                 }
                 printf("\n");
         }
 }