PSU_zappy_2017: server/src/rfc_cmds0.c File Reference
rfc_cmds0.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include "../include/server.h"
Functions
void * join (cmdargs args, int clifd, t_teams *chans)
void * nick (cmdargs args, int clifd, t_teams *chans)
void * ping (cmdargs args, int clifd, t_teams *chans)
void * user (cmdargs args, int clifd, t_teams *chans)
void * quit (cmdargs args, int clifd, t_teams *chans)
Function Documentation
join()
void* join (cmdargs args, int clifd, t_teams * chans)
The JOIN #<teams> command handler
Parameters
args the JOIN arguments, composed of the teams name started by '#'
clifd the client file descriptor
chans the main teams doubly linked list (updated if new teams)
Returns
chans the head pointer of the teams list passed in params
Note
see RFC 2812 part 3.2.1
Definition at line 19 of file rfc_cmds0.c.
References find_user_by_fd(), get_new_chan_list(), get_new_userlist(), get_team_by_name(), insert_back_teams(), insert_back_user(), t_userlist::next, and t_teams::users.
 {
         t_user *usr = find_user_by_fd(chans->users, clifd);
         t_userlist *list = get_new_userlist(usr);
         t_teams *rchan = get_team_by_name(chans, args[1]);
         if (usr) {
                 if (!rchan) {
                 rchan = get_new_chan_list(list, args[1]);
                 chans = insert_back_teams(chans, rchan);
                 } else if (!find_user_by_fd(rchan->users, clifd)) {
                         rchan->users = insert_back_user(rchan->users, list);
                 }
                 for (t_userlist *b = rchan->users; b; b = b->next) {
                         dprintf(b->user->clifd, ":%s JOIN :%s\r\n", usr->nick, args[1]);
                 }
                 dprintf(clifd, ":server 331\r\n%s: no topic is set\r\n", args[1]);
         }
         return (chans);
 }
nick()
void* nick (cmdargs args, int clifd, t_teams * chans)
The NICK <nickname> command handler handler
Parameters
args the NICK arguments, composed of the requested username
clifd the client file descriptor (unusued)
chans the main teams doubly linked list (unusued)
Returns
chans the head pointer of the teams list passed in params
Note
stil missing the update username and the error messages if nickname already in use, invalid nickname etc .. (see RFC 2812 part 3.1.2)
Definition at line 48 of file rfc_cmds0.c.
References t_userlist::next, and t_teams::users.
 {
         char *fmt = ":BrokenIRC NICK %s\r\n";
         if (clifd)
         for (t_userlist *tmp = chans->users; tmp; tmp = tmp->next) {
                         dprintf(tmp->user->clifd, fmt, args[1]);
         }
         return (chans);
 }
ping()
void* ping (cmdargs args, int clifd, t_teams * chans)
The PING <server address>=""> command handler
Parameters
args the PING arguments, composed of the above arguments
clifd the client file descriptor (unusued)
chans the main teams doubly linked list (unusued)
Returns
chans the head pointer of the teams list passed in params
Note
simply answer PONG followed by the conventionnal EOL symbol
Definition at line 67 of file rfc_cmds0.c.
 {
         if (args || !args || chans)
         dprintf(clifd, "PONG\r\n");
         return (chans);
 }
quit()
void* quit (cmdargs args, int clifd, t_teams * chans)
The QUIT <quit message>=""> command handler
Parameters
args the QUIT arguments, composed of the above args
clifd the client file descriptor
chans the main teams doubly linked list (updated if new teams)
Returns
chans the head pointer of the teams list passed in params
Note
still a bit buggy on the remove_user() part (run and see by urself)
Definition at line 103 of file rfc_cmds0.c.
References find_user_by_fd(), is_user_in_chan(), t_userlist::next, t_teams::next, and t_teams::users.
 {
         t_user *usr = find_user_by_fd(chans->users, clifd);
         if (usr) {
                 for (t_userlist *b = chans->users; b; b = b->next) {
                         dprintf(b->user->clifd, ":%s QUIT :%s\r\n", usr->nick, args[1]);
                 }
                 for (t_teams *chan = chans; chan; chan = chan->next) {
                         is_user_in_chan(clifd, chan);
                 }
         }
         close(clifd);
         return (chans);
 }
user()
void* user (cmdargs args, int clifd, t_teams * chans)
The USER <username> <mode> <unusued> <realname> command handler
Parameters
args the JOIN arguments, composed of the above args
clifd the client file descriptor
chans the main teams doubly linked list, updated by pushback'ing the new user in chan->users list
Returns
chans the head pointer of the teams list passed in params
Note
Still missing a lot of check for size, dublons etc etc and also the <mode> handling (invisible etc) see RFC 2812 part 3.1.3
Definition at line 83 of file rfc_cmds0.c.
References get_new_user(), get_new_userlist(), get_size(), insert_back_user(), and t_teams::users.
Referenced by send_egg_death(), send_egg_hatch(), send_expulsion(), send_res_collect(), and send_res_drop().
 {
         char *banneer = "|| Welcome to BrokenIRC Network || ";
         if (get_size(args) == 5) {
                 t_user *usr = get_new_user(clifd, args);
                 t_userlist *list = get_new_userlist(usr);
                 chans->users = insert_back_user(chans->users, list);
                 dprintf(clifd, "001 :%s %s %s\r\n", args[1], args[1], banneer);
         }
         return (chans);
 }