BrokenIRC: server_src/rfc_cmds1.c File Reference
rfc_cmds1.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include "../include/server.h"
Functions
static char * get_full_msg (char **args)
void * broadcast_msg (t_channel *reqchan, char **message, int clifd)
void * privmsg (cmdargs args, int clifd, t_channel *chans)
Detailed Description
See
Definition in file rfc_cmds1.c.
Function Documentation
broadcast_msg()
void* broadcast_msg (t_channel * reqchan, char ** message, int clifd)
Definition at line 30 of file rfc_cmds1.c.
References t_userlist::next, and t_channel::users.
Referenced by privmsg().
 {
         t_userlist *broadcast_list =  reqchan ? reqchan->users : NULL;
         if (broadcast_list)
                 for (t_userlist *tmp = broadcast_list; tmp; tmp = tmp->next) {
                         if (tmp->user->clifd != clifd) {
                         dprintf(tmp->user->clifd, ":%s PRIVMSG %s %s\r\n",
                         message[1], message[2], message[0]);
                         }
                 }
         return (NULL);
 }
get_full_msg()
static char* get_full_msg (char ** args) static
Self explanatory
Parameters
args the splitted message
Returns
the constructed string
Note
missing check for buffer size, escape sequence, malicious message etc see RFC 2812 part 3.3.1 and how to check for bogus or malicious chars
Definition at line 18 of file rfc_cmds1.c.
References BUF_SIZE.
Referenced by privmsg().
 {
         char *msg = malloc(BUF_SIZE);
         memset(msg, 0, BUF_SIZE);
         for (int i = 2; args[i]; ++i) {
                 strcat(msg, args[i]);
                 strcat(msg, " ");
         }
         return (msg);
 }
privmsg()
void* privmsg (cmdargs args, int clifd, t_channel * chans)
The PRIVMSG <msgtarget> <message> command
Parameters
args the PRIVMSG arguments, see above
clifd the client file descriptor
chans the main channel doubly linked list (updated if new channel)
Returns
chans the head pointer of the channel list passed in params
Note
as get_args() split by space we need to reconstruct the original message with the get_full_msg() method
Todo:
for now, message can only be sent to a channel , missing the message a user function
Definition at line 54 of file rfc_cmds1.c.
References broadcast_msg(), t_user::clifd, find_user_by_fd(), find_user_by_name(), get_chan_by_name(), get_full_msg(), t_user::nick, and t_channel::users.
 {
         t_user *from = find_user_by_fd(chans->users, clifd);
         t_channel *reqchan = get_chan_by_name(chans, args[1]);
         t_user *to = reqchan ? NULL : find_user_by_name(args[1], chans->users);
         char *message[3] = { get_full_msg(args), from->nick, args[1] };
         if (reqchan) {
                 broadcast_msg(reqchan, message, clifd);
         } else if (to) {
                 dprintf(to->clifd, ":%s PRIVMSG %s %s\r\n",
                         message[1], message[2], message[0]);
         }
         free(message[0]);
         return (chans);
 }