PSU_zappy_2017: include/server.h File Reference
server.h File Reference
#include <stdio.h>
#include <netdb.h>
#include <string.h>
#include <sys/epoll.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include "zappy_game.h"
Data Structures
struct t_log
struct t_clargs
struct t_serv
struct t_user
struct t_userlist
struct t_teams
Macros
#define BACKLOG 10
#define REF_NB 13
#define BUF_SIZE 1060
#define MAX_EVENTS 10
#define MAXTEAMS 1000
#define MAXARGS 15
#define MAXARGSIZE 33
#define NI_MAXHOST 1025
#define NI_MAXSERV 32
#define EVER ;;
#define true 1
#define false 0
Typedefs
typedef char ** cmdargs
typedef struct addrinfo adrinf
typedef void *(* cmds) (cmdargs args, int clifd, t_teams *chanlist)
typedef void *(* clargs) (char **, t_clargs *)
Enumerations
enum CMDS {
FORWARD, RIGHT, LEFT, LOOK,
INVENTORY, BROADCAST_TEXT, CONNECT_NBR, FORK,
EJECT, TAKE_OBJECT, SET_OBJECT, INCANTATION
}
enum LPATHS { ACCESS, ERRORS, NOTICES }
Functions
int set_sockfd (t_serv *all)
int set_epoll (t_serv *all)
int set_iface (adrinf *hints, adrinf **res, const char *port)
int set_clifd (int clisock, int epollfd, struct epoll_event *ev)
int server (t_clargs *options)
int get_methods (char *req, int clifd)
int logthisevent (const char etype, t_serv *all)
void print_users (t_userlist *list)
void print_users_in_chans (t_teams *chanlist, int index)
t_userlist * get_new_userlist (t_user *usr)
void free_userlist (t_userlist *list)
void * remove_user (t_userlist *list, int clifd)
t_user * get_new_user (int clifd, cmdargs usercmd)
void * insert_back_user (t_userlist *head, t_userlist *nuser)
t_teams * init_default_teams (void)
void free_teams_list (t_teams *list)
t_teams * get_new_chan_list (t_userlist *userlist, char *)
void remove_teams (t_teams *list, char *channame)
void * insert_back_teams (t_teams *head, t_teams *chan)
t_user * find_user_by_fd (t_userlist *list, int clifd)
t_user * find_user_by_name (const char *name, t_userlist *usrs)
t_teams * get_team_by_name (t_teams *list, char *channame)
unsigned int is_user_in_chan (int clifd, t_teams *chans)
unsigned int get_size (cmdargs args)
void * join (cmdargs args, int clifd, t_teams *chanlist)
void * nick (cmdargs args, int clifd, t_teams *chanlist)
void * ping (cmdargs args, int clifd, t_teams *chanlist)
void * user (cmdargs args, int clifd, t_teams *chanlist)
void * quit (cmdargs args, int clifd, t_teams *chanlist)
void * privmsg (cmdargs args, int clifd, t_teams *chans)
void * get_port (char **port, t_clargs *args)
void * get_width (char **width, t_clargs *args)
void * get_height (char **height, t_clargs *args)
void * get_teams (char **teams, t_clargs *args)
void * get_clientsNb (char **clientsNb, t_clargs *args)
void * get_freq (char **freq, t_clargs *args)
t_clargs * get_opts (int ac, char **av)
clargs * set_opts ()
void free_buffers (char **buffer)
void sig_handler (int signo)
void usage (char *progname)
t_world * get_world (t_clargs *args)
void free_world (t_world *trantor, t_clargs *args)
Variables
const char * G_PROTOS [REF_NB]
const cmds G_CMDS [REF_NB]
Macro Definition Documentation
BACKLOG
#define BACKLOG 10
Number of simultaneous connection on server listening socket see listen() call
Definition at line 22 of file server.h.
Referenced by set_sockfd().
BUF_SIZE
#define BUF_SIZE 1060
This good old C mem alloc dirty method
Definition at line 26 of file server.h.
Referenced by get_full_msg(), and getactiveclients().
EVER
#define EVER ;;
Yess useless so mandatory
Definition at line 50 of file server.h.
Referenced by get_time(), and server().
false
#define false 0
Definition at line 116 of file server.h.
MAX_EVENTS
#define MAX_EVENTS 10
The length of the struct epoll_events array pointed to by *events
Definition at line 30 of file server.h.
Referenced by server().
MAXARGS
#define MAXARGS 15
Maximum number of args in a single command
Definition at line 35 of file server.h.
Referenced by get_args(), and get_commands().
MAXARGSIZE
#define MAXARGSIZE 33
Maximum argument length see ref below
Note
obtained by 500 / max args
Definition at line 39 of file server.h.
MAXTEAMS
#define MAXTEAMS 1000
Max teams
Definition at line 33 of file server.h.
Referenced by get_teams().
NI_MAXHOST
#define NI_MAXHOST 1025
Maximal size for a client IP address
Definition at line 41 of file server.h.
Referenced by get_host_string().
NI_MAXSERV
#define NI_MAXSERV 32
Maximal size for a client host port
Definition at line 43 of file server.h.
Referenced by get_host_string().
REF_NB
#define REF_NB 13
Number of Zappy command
Definition at line 24 of file server.h.
Referenced by get_methods().
true
#define true 1
To avoid stdbool include (for s_user.isco)
Definition at line 115 of file server.h.
Typedef Documentation
adrinf
typedef struct addrinfo adrinf
Yeah simplification
Definition at line 94 of file server.h.
clargs
typedef void*(* clargs) (char **, t_clargs *)
The flags 'gatherer' function pointer
Note
see server_src/cl_args_helpers.c
Definition at line 150 of file server.h.
cmdargs
typedef char** cmdargs
Argument format typedef as per subject request
Note
Useless typedef came from a deprecated method, but hey too lazy to rename all
Definition at line 48 of file server.h.
cmds
typedef void*(* cmds) (cmdargs args, int clifd, t_teams *chanlist)
Main Zappy Protocol methods function pointer
Note
see server_src/server_decls.c
Definition at line 146 of file server.h.
Enumeration Type Documentation
CMDS
enum CMDS
Only here for code clarity and lisibility
Todo:
: Have a look at ZAPPY_CMDS.md file for ref
Enumerator
FORWARD
RIGHT
LEFT
LOOK
INVENTORY
BROADCAST_TEXT
CONNECT_NBR
FORK
EJECT
TAKE_OBJECT
SET_OBJECT
INCANTATION
Definition at line 55 of file server.h.
                    {
                 FORWARD, RIGHT, LEFT,
                 LOOK, INVENTORY, BROADCAST_TEXT,
                 CONNECT_NBR, FORK, EJECT,
                 TAKE_OBJECT, SET_OBJECT, INCANTATION
         };
LPATHS
enum LPATHS
Enumerator
ACCESS
ERRORS
NOTICES
Definition at line 63 of file server.h.
                      {
                 ACCESS,
                 ERRORS,
                 NOTICES
         };
Function Documentation
find_user_by_fd()
t_user* find_user_by_fd (t_userlist * list, int clifd)
Note
see server_src/list_helpers.c
Find a t_user structure pointer if clientfd exist inside
Parameters
list the full userlist
clifd the 'to find' client fd
Returns
user if clientfd exist in the list
NULL pointer if nothing found
Definition at line 30 of file lists_finders.c.
References t_userlist::next.
Referenced by join(), privmsg(), and quit().
 {
         t_user *usr = NULL;
         for (t_userlist *tmp = list; tmp; tmp = tmp->next) {
                 if (tmp->user->clifd == clifd) {
                         usr = tmp->user;
                         break;
                 }
         }
         return (usr);
 }
find_user_by_name()
t_user* find_user_by_name (const char * name, t_userlist * usrs)
Find a user by name literaly
Parameters
name the name to find
Definition at line 76 of file lists_finders.c.
References t_userlist::next.
Referenced by privmsg().
 {
         t_user *needle = NULL;
         for (t_userlist *foo = usrs; foo; foo = foo->next) {
                 if (!strcmp(name, foo->user->nick) ||
                 !strcmp(name, foo->user->rname)) {
                         needle = foo->user;
                         break;
                 }
         }
         return (needle);
 }
free_buffers()
void free_buffers (char ** buffer)
Free the token list
Parameters
buffer the 2D array to be free'd
Definition at line 14 of file cl_args_helpers.c.
Referenced by get_methods(), and get_opts().
 {
         int i;
         for (i = 0; buffer[i]; ++i) {
                 free(buffer[i]);
         }
         free(buffer);
 }
free_teams_list()
void free_teams_list (t_teams * list)
Self explanatory
Parameters
list the list to be de-allocated
Definition at line 74 of file teams_list.c.
References free_userlist(), t_teams::next, and t_teams::users.
 {
         while (list) {
                 free_userlist(list->users);
                 t_teams *next = list->next;
                 free(list);
                 list = next;
         }
 }
free_userlist()
void free_userlist (t_userlist * list)
Self explanatory
Parameters
list the list to be freed
Definition at line 98 of file user_list.c.
References t_userlist::next, t_user::nick, t_user::rname, and t_userlist::user.
Referenced by free_teams_list(), and remove_teams().
 {
         while (list) {
                 free(list->user->rname);
                 free(list->user->nick);
                 free(list->user);
                 t_userlist *next = list->next;
                 free(list);
                 list = next;
         }
 }
free_world()
void free_world (t_world * trantor, t_clargs * args)
Free the t_world ptr with the 2D t_tile array inside
Parameters
trantor the world pointer to be freed
args the command line args to have the map size
Definition at line 16 of file world_creation.c.
References t_clargs::height, and t_world::tiles.
Referenced by get_world().
 {
         t_tile **tmp = trantor->tiles;
         for (int i = 0; i < args->height; ++i) {
                 free(tmp[i]);
         }
         free(tmp);
         free(trantor);
 }
get_clientsNb()
void* get_clientsNb (char ** clientsNb, t_clargs * args)
Get -c flag, the number of clients(aka players) per teams
Parameters
clientsNb the received arguments to flag
args the t_clargs struct to fill with clientsNb value
Definition at line 33 of file cl_flags_bis.c.
References t_clargs::clientsNb.
Referenced by set_opts().
 {
         #ifdef CLDBG
                 printf("\t%s\n", "get_clientsNb ouh yeah!");
                 print_2d(clientsNb);
         #endif
         args->clientsNb = atoi(clientsNb[1]);
         return (args->clientsNb >= 0 ? args : NULL);
 }
get_freq()
void* get_freq (char ** freq, t_clargs * args)
Get -f flag, the frequency of blablabla
Parameters
freq the received argument to flag
args the t_clargs struct to fill with frequency value
Definition at line 47 of file cl_flags_bis.c.
References t_clargs::freq.
Referenced by set_opts().
 {
         #ifdef CLDBG
                 printf("\t%s\n", "get_freq ouh yeah!");
                 print_2d(freq);
         #endif
         args->freq = atoi(freq[1]);
         return (args->freq >= 0 ? args : NULL);
 }
get_height()
void* get_height (char ** height, t_clargs * args)
Get -y flag, the map height
Parameters
height the received argument to flag
args the t_clargs struct to fill with height value
Definition at line 45 of file cl_flags.c.
References t_clargs::height.
Referenced by set_opts().
 {
         #ifdef CLDBG
                 printf("\t%s\n", "get_height ouh yeah!");
                 print_2d(height);
         #endif
         args->height = atoi(height[1]);
         return (args->height >= 0 ? args : NULL);
 }
get_methods()
int get_methods (char * req, int clifd)
Note
see server_src/commands_parsing.c
Match all methods in G_CMDS for a given req command string
Parameters
req the readed commands buffer
clifd the client socket fd
Note
could add compilation macro for debug print_2darray() calls but epitech norm insist on 20 line per function so ...
Definition at line 60 of file commands_parsing.c.
References free_buffers(), G_CMDS, G_PROTOS, get_args(), get_commands(), init_default_teams(), print_users_in_chans(), and REF_NB.
Referenced by events_handler().
 {
         int index = 0;
         char **cmds = get_commands(req);
         char **args = NULL;
         static t_teams *defchan = NULL;
         defchan = !defchan ? init_default_teams() : defchan;
         for (int j = 0; cmds[j]; ++j) {
                 for (index = 0; G_PROTOS[index]; ++index) {
                         if ((strstr(cmds[j], G_PROTOS[index]))) {
                                 args = get_args(cmds[j]);
                                 G_CMDS[index](args, clifd, defchan);
                                 free_buffers(args);
                                 break;
                         }
                 }
         }
         print_users_in_chans(defchan, index);
         free_buffers(cmds);
         return ((index == REF_NB) ? (0) : (index));
 }
get_new_chan_list()
t_teams* get_new_chan_list (t_userlist * userlist, char * channame)
Self explanatory
Parameters
userlist the userlist to insert in the new teams element
channame the new teams name
Definition at line 15 of file teams_list.c.
References t_teams::channame, t_teams::next, t_teams::prev, and t_teams::users.
Referenced by join().
 {
         t_teams *list = malloc(sizeof(*list));
         if (list) {
                 memset(list, 0, sizeof(*list));
                 list->users = userlist;
                 list->channame = strdup(channame);
                 list->prev = NULL;
                 list->next = NULL;
         }
         return (list);
 }
get_new_user()
t_user* get_new_user (int clifd, cmdargs usercmd)
Malloc and memset a new t_user element
Parameters
clifd the user client file descriptor
usercmd the USER <space> args 2d array
Returns
list the new element
Definition at line 16 of file user_list.c.
References t_user::clifd, t_user::mode, t_user::nick, and t_user::rname.
Referenced by init_default_teams(), and user().
 {
         t_user *usr = malloc(sizeof(*usr));
         if (usr) {
                 memset(usr, 0, sizeof(*usr));
                 usr->clifd = clifd;
                 usr->mode = atoi(usercmd[2]);
                 usr->nick = strdup(usercmd[1]);
                 usr->rname = strdup(usercmd[4]);
         }
         return (usr);
 }
get_new_userlist()
t_userlist* get_new_userlist (t_user * usr)
Note
see server_src/client_list.c
Malloc and memset a new userlist element
Parameters
usr the t_user on the userlist
Returns
list the new element
Definition at line 34 of file user_list.c.
References t_userlist::next, t_userlist::prev, and t_userlist::user.
Referenced by init_default_teams(), join(), and user().
 {
         t_userlist *list = malloc(sizeof(*list));
         if (list) {
                 memset(list, 0, sizeof(*list));
                 list->user = usr;
                 list->prev = NULL;
                 list->next = NULL;
         }
         return (list);
 }
get_opts()
t_clargs* get_opts (int ac, char ** av)
Note
see server_src/cl_args.c
Parse command line args flags from av[] and store it in a t_clargs struct
Parameters
ac the number of received params
av the 2d char array from main()
Returns
args the storage struct
NULL if errors
Note
consider refactoring / splitting this function as it's 2 lines above the 20's authorized by this silly/f**ing norm. Variables are also uncorrectly declared. We also could do a 'trash bin struct' for all args
Definition at line 100 of file cl_args_parsing.c.
References free_buffers(), get_args(), get_cmdargs(), get_req(), main(), set_default_args(), and set_opts().
Referenced by main().
 {
         t_clargs        *args = set_default_args();
         clargs          *opts = set_opts();
         char            *req = get_req(ac, av);
         char            **cmd_args = NULL;
         char            *token;
         char            *saveptr1, *saveptr2;
         int             index = 0;
         if (args && req) {
                 for (; ; req = NULL) {
                         token = strtok_r(req, "-", &saveptr1);
                         if (token == NULL) {
                                 break;
                         } else {
                                 index = token[0];
                                 cmd_args = get_cmdargs(token, &saveptr2);
                                 cmd_args ? opts[index](cmd_args, args) : opts;
                                 cmd_args ? free_buffers(cmd_args) : cmd_args;
                         }
                 }
         }
         return (args);
 }
get_port()
void* get_port (char ** port, t_clargs * args)
Note
See server_src/cl_flags.c
Get -p flag, the requested listening port for server
Parameters
port the received argument to flag
args the t_clargs struct to fill with port value
Definition at line 15 of file cl_flags.c.
References t_clargs::port.
Referenced by set_opts().
 {
         int rt = 0;
         #ifdef CLDBG
                 printf("\t\t%s\n", "get_port()");
                 print_2d(port);
         #endif
         args->port = strdup(port[1]);
         rt = atoi(port[1]);
         return (rt >= 1024 ? args : NULL);
 }
get_size()
unsigned int get_size (cmdargs args)
Get the size of a 2d Array
Returns
i the size of the cmdargs 2d char *array
Definition at line 14 of file lists_finders.c.
Referenced by user().
 {
         unsigned int i = 0;
         while (args[i]) {
                 ++i;
         }
         return (i);
 }
get_team_by_name()
t_teams* get_team_by_name (t_teams * list, char * channame)
Get the t_teams pointer by its name
Parameters
list the teams list
channame the resquested teams
Returns
a t_teams pointer if exists , NULL otherwise
Definition at line 48 of file lists_finders.c.
References t_teams::next.
Referenced by join(), and privmsg().
 {
         t_teams *rt = NULL;
         for (t_teams *tmp = list; tmp; tmp = tmp->next) {
                 if (!strcmp(tmp->channame, channame)) {
                         rt = tmp;
                         break;
                 }
         }
         return (rt);
 }
get_teams()
void* get_teams (char ** teams, t_clargs * args)
Note
see server_src/cl_flags_bis.c
Get -n flag, the teams name
Parameters
teams the received argument to flag
args the t_clargs struct to fill with teams names values
Definition at line 15 of file cl_flags_bis.c.
References MAXTEAMS, and t_clargs::teams_names.
Referenced by set_opts().
 {
         unsigned int size = 0;
         #ifdef CLDBG
                 printf("\t%s\n", "get_teams ouh yeah!");
                 print_2d(teams);
         #endif
         args->teams_names = malloc(MAXTEAMS);
         for (size = 1; teams[size]; ++size) {
                 args->teams_names[size - 1] = strdup(teams[size]);
         }
         return (size > 0 ? args : NULL);
 }
get_width()
void* get_width (char ** width, t_clargs * args)
Get -x flag, the map width
Parameters
width the received argument to flag
args the t_clargs struct to fill with width value
Definition at line 31 of file cl_flags.c.
References t_clargs::width.
Referenced by set_opts().
 {
         #ifdef CLDBG
                 printf("\t\t%s\n", "get_width()");
                 print_2d(width);
         #endif
         args->width = atoi(width[1]);
         return (args->width >= 0 ? args : NULL);
 }
get_world()
t_world* get_world (t_clargs * args)
See server_src/trantor_setup/world_creation
Setup the trantor world map
Parameters
args the args pointer containing the map size
Returns
trantor the setup'ed map
Definition at line 68 of file world_creation.c.
References t_ressources::food, free_world(), get_tiles(), get_world(), t_clargs::height, main(), t_food::qtt, t_tile::ressources, t_world::tiles, and t_clargs::width.
Referenced by get_world().
 {
         t_world *trantor = malloc(sizeof(*trantor));
         if (trantor) {
                 trantor->tiles = get_tiles(args->width, args->height);
         }
         return (trantor);
 }
init_default_teams()
t_teams* init_default_teams (void)
Note
see server_src/teams_list.c
Self explanatory
Returns
the default teams where all user resides
Note
the teams name, the default user and all could be parsed from a config file (#pullrequestIdea)
Definition at line 89 of file teams_list.c.
References t_teams::channame, get_new_user(), get_new_userlist(), t_teams::next, t_teams::prev, and t_teams::users.
Referenced by get_methods().
 {
         char *defuser[5] = {"NICK", "4Dm1n", "42", "*", ":John Doe"};
         t_teams *defchan = malloc(sizeof(*defchan));
         t_user *admin = get_new_user(0, defuser);
         t_userlist *allusers = get_new_userlist(admin);
         if (defchan && admin && allusers) {
                 defchan->channame = "#welcome";
                 defchan->users = allusers;
                 defchan->prev = NULL;
                 defchan->next = NULL;
         }
         return (defchan);
 }
insert_back_teams()
void* insert_back_teams (t_teams * head, t_teams * new)
Push back a new teams element to the main list container
Parameters
head the head pointer
new the new teams element to be inserted
Definition at line 33 of file teams_list.c.
References t_teams::next.
Referenced by join().
 {
         t_teams *tmp = head;
         if (!head) {
                 head = new;
         } else {
                 while (tmp->next) {
                         tmp = tmp->next;
                 }
                 tmp->next = new;
                 new->prev = tmp;
         }
         return (head);
 }
insert_back_user()
void* insert_back_user (t_userlist * head, t_userlist * nuser)
Push back a n(ew)user in the userlist head
Parameters
head the userlist to be modified
nuser the n(ew)user to be inserted
Returns
head the head pointer
Definition at line 52 of file user_list.c.
References t_userlist::next, and t_userlist::prev.
Referenced by join(), and user().
 {
         t_userlist *tmp = head;
         if (!head) {
                 head = nuser;
         } else {
                 while (tmp->next) {
                         tmp = tmp->next;
                 }
                 tmp->next = nuser;
                 nuser->prev = tmp;
         }
         return (head);
 }
is_user_in_chan()
unsigned int is_user_in_chan (int clifd, t_teams * chans)
Definition at line 61 of file lists_finders.c.
References t_teams::channame, t_userlist::next, and t_teams::users.
Referenced by quit().
 {
         for (t_userlist *usrs = chans->users; usrs; usrs = usrs->next) {
                 if (clifd == usrs->user->clifd) {
                         printf("Chan name [%s] Is in list ? [%s]\n",
                         chans->channame, usrs->user->nick);
                         usrs->user->isco = false;
                 }
         }
         return (1);
 }
join()
void* join (cmdargs args, int clifd, t_teams * chans)
The JOIN #<teams> command handler
Parameters
args the JOIN arguments, composed of the teams name started by '#'
clifd the client file descriptor
chans the main teams doubly linked list (updated if new teams)
Returns
chans the head pointer of the teams list passed in params
Note
see RFC 2812 part 3.2.1
Definition at line 19 of file rfc_cmds0.c.
References find_user_by_fd(), get_new_chan_list(), get_new_userlist(), get_team_by_name(), insert_back_teams(), insert_back_user(), t_userlist::next, t_user::nick, and t_teams::users.
 {
         t_user *usr = find_user_by_fd(chans->users, clifd);
         t_userlist *list = get_new_userlist(usr);
         t_teams *rchan = get_team_by_name(chans, args[1]);
         if (usr) {
                 if (!rchan) {
                 rchan = get_new_chan_list(list, args[1]);
                 chans = insert_back_teams(chans, rchan);
                 } else if (!find_user_by_fd(rchan->users, clifd)) {
                         rchan->users = insert_back_user(rchan->users, list);
                 }
                 for (t_userlist *b = rchan->users; b; b = b->next) {
                         dprintf(b->user->clifd, ":%s JOIN :%s\r\n", usr->nick, args[1]);
                 }
                 dprintf(clifd, ":server 331\r\n%s: no topic is set\r\n", args[1]);
         }
         return (chans);
 }
logthisevent()
int logthisevent (const char etype, t_serv * all)
Note
see server_src/logs_helpers.c
Switch type and print data in t_serv according to a fmt string
Parameters
etype the kind of event type in [C]onnect, [D]isconnect or default
all the 'catch them all' structure with server infos
Returns
1
Definition at line 58 of file logs_helpers.c.
References t_serv::buf, get_host_string(), t_serv::host, t_serv::nread, and t_serv::service.
Referenced by events_handler().
 {
         char *usr = get_host_string(all->host, all->service);
         char *c_fmt = " = > IN: [%zd bytes] FROM: [%s] DATA: [%s]\n";
         char *d_fmt = "USER: [%s] disconnect\n";
         char *def_fmt = "Type:%c Size:%zd DATA: [%s]\n";
         switch (etype) {
                 case 'c':
                         fprintf(stdout, c_fmt, all->nread, usr, all->buf);
                         break;
                 case 'd':
                         fprintf(stdout, d_fmt, usr);
                         break;
                 default:
                         fprintf(stdout, def_fmt, etype, all->nread, all->buf);
                         break;
         }
         free(usr);
         return (1);
 }
nick()
void* nick (cmdargs args, int clifd, t_teams * chans)
The NICK <nickname> command handler handler
Parameters
args the NICK arguments, composed of the requested username
clifd the client file descriptor (unusued)
chans the main teams doubly linked list (unusued)
Returns
chans the head pointer of the teams list passed in params
Note
stil missing the update username and the error messages if nickname already in use, invalid nickname etc .. (see RFC 2812 part 3.1.2)
Definition at line 48 of file rfc_cmds0.c.
References t_userlist::next, and t_teams::users.
 {
         char *fmt = ":BrokenIRC NICK %s\r\n";
         if (clifd)
         for (t_userlist *tmp = chans->users; tmp; tmp = tmp->next) {
                         dprintf(tmp->user->clifd, fmt, args[1]);
         }
         return (chans);
 }
ping()
void* ping (cmdargs args, int clifd, t_teams * chans)
The PING <server address>=""> command handler
Parameters
args the PING arguments, composed of the above arguments
clifd the client file descriptor (unusued)
chans the main teams doubly linked list (unusued)
Returns
chans the head pointer of the teams list passed in params
Note
simply answer PONG followed by the conventionnal EOL symbol
Definition at line 67 of file rfc_cmds0.c.
 {
         if (args || !args || chans)
         dprintf(clifd, "PONG\r\n");
         return (chans);
 }
print_users()
void print_users (t_userlist * list)
Print users nick and real name stored in a t_userlist doubly linked list
Parameters
liste the t_userlist to print
Definition at line 29 of file logs_helpers.c.
References t_userlist::next.
Referenced by print_users_in_chans().
 {
         printf("\t\tUSERS LIST :\n");
         for (t_userlist *tmp = list; tmp; tmp = tmp->next) {
                 printf("User : [%s], Real Name : [%s]\n",
                 tmp->user->nick, tmp->user->rname);
         }
         printf("\n");
 }
print_users_in_chans()
void print_users_in_chans (t_teams * chanlist, int index)
Print each teams in list with its users
Parameters
chanlist the teamss doubly linked list
index the received command index to avoid printing each time a PING cmd is received (too much log ;))
Definition at line 17 of file logs_helpers.c.
References t_teams::next, and print_users().
Referenced by get_methods().
 {
         if (index)
         for (t_teams *tmp = chanlist; tmp; tmp = tmp->next) {
                 printf("\tteams : [%s]\n", tmp->channame);
                 print_users(tmp->users);
         }
 }
privmsg()
void* privmsg (cmdargs args, int clifd, t_teams * chans)
Note
see server_src/rfc_cmds1.c
The PRIVMSG <msgtarget> <message> command
Parameters
args the PRIVMSG arguments, see above
clifd the client file descriptor
chans the main teams doubly linked list (updated if new teams)
Returns
chans the head pointer of the teams list passed in params
Note
as get_args() split by space we need to reconstruct the original message with the get_full_msg() method
Todo:
for now, message can only be sent to a teams , missing the message a user function
Definition at line 54 of file rfc_cmds1.c.
References broadcast_msg(), t_user::clifd, find_user_by_fd(), find_user_by_name(), get_full_msg(), get_team_by_name(), t_user::nick, and t_teams::users.
 {
         t_user *from = find_user_by_fd(chans->users, clifd);
         t_teams *reqchan = get_team_by_name(chans, args[1]);
         t_user *to = reqchan ? NULL : find_user_by_name(args[1], chans->users);
         char *message[3] = { get_full_msg(args), from->nick, args[1] };
         if (reqchan) {
                 broadcast_msg(reqchan, message, clifd);
         } else if (to) {
                 dprintf(to->clifd, ":%s PRIVMSG %s %s\r\n",
                         message[1], message[2], message[0]);
         }
         free(message[0]);
         return (chans);
 }
quit()
void* quit (cmdargs args, int clifd, t_teams * chans)
The QUIT <quit message>=""> command handler
Parameters
args the QUIT arguments, composed of the above args
clifd the client file descriptor
chans the main teams doubly linked list (updated if new teams)
Returns
chans the head pointer of the teams list passed in params
Note
still a bit buggy on the remove_user() part (run and see by urself)
Definition at line 103 of file rfc_cmds0.c.
References find_user_by_fd(), is_user_in_chan(), t_userlist::next, t_teams::next, t_user::nick, and t_teams::users.
 {
         t_user *usr = find_user_by_fd(chans->users, clifd);
         if (usr) {
                 for (t_userlist *b = chans->users; b; b = b->next) {
                         dprintf(b->user->clifd, ":%s QUIT :%s\r\n", usr->nick, args[1]);
                 }
                 for (t_teams *chan = chans; chan; chan = chan->next) {
                         is_user_in_chan(clifd, chan);
                 }
         }
         close(clifd);
         return (chans);
 }
remove_teams()
void remove_teams (t_teams * list, char * channame)
Remove a teams element from the doubly linked list
Parameters
list the userlist to be updated
channame the teams name to be deleted
Definition at line 53 of file teams_list.c.
References t_teams::channame, free_userlist(), t_teams::next, t_teams::prev, and t_teams::users.
 {
         t_teams *tmp = list;
         while (tmp->next != NULL)
         {
                 if (!strcmp(tmp->channame, channame)) {
                         tmp->prev->next = tmp->next;
                         tmp->next->prev = tmp->prev;
                         free_userlist(tmp->users);
                         free(tmp->channame);
                         free(tmp);
                         break;
                 }
                 tmp = tmp->next;
         }
 }
remove_user()
void* remove_user (t_userlist * list, int clifd)
Remove a user from a userlist
Parameters
list the userlist to be updated
clifd the clientfd as index for element to be removed
Returns
list the updated userlist
Definition at line 73 of file user_list.c.
References t_user::clifd, t_userlist::next, t_user::nick, t_userlist::prev, t_user::rname, and t_userlist::user.
 {
         t_userlist *tmp = list;
         while (tmp) {
                 if (tmp->user->clifd == clifd) {
                         tmp->prev->next = tmp->next;
                         if (tmp->next)
                                 tmp->next->prev = tmp->prev;
                         else
                                 tmp->next = NULL;
                         free(tmp->user->rname);
                         free(tmp->user->nick);
                         free(tmp->user);
                         free(tmp);
                         break;
                 }
                 tmp = tmp->next;
         }
         return (list);
 }
server()
int server (t_clargs * options)
Note
see server_src/server_main.c
Contain the main server infinite loop
Parameters
options the server and game settings received from main()
Todo:
read the various notes on documentation and do what requested
Definition at line 95 of file server_main.c.
References t_serv::epollfd, t_serv::events, EVER, getactiveclients(), t_serv::hints, t_serv::listen_sock, MAX_EVENTS, t_serv::nfds, t_clargs::port, t_serv::res, set_epoll(), set_iface(), and set_sockfd().
Referenced by main().
 {
         int rt = 0;
         t_serv all;
         set_iface(&all.hints, &all.res, options->port);
         all.listen_sock = set_sockfd(&all);
         if (all.listen_sock < 0 || set_epoll(&all) == -1) {
                 rt = 84;
         } else {
                 for (EVER) {
                         all.nfds = epoll_wait(all.epollfd, all.events,
                                 MAX_EVENTS, -1);
                         if (all.nfds == -1) {
                                 perror("server: epoll_wait");
                                 break;
                         }
                         rt = getactiveclients(&all);
                 }
                 close(all.listen_sock);
         }
         return (rt);
 }
set_clifd()
int set_clifd (int clisock, int epollfd, struct epoll_event * ev)
Add the new client file descriptor in struct epoll_event structure for polling their events read this medium blog post on 'epoll madness'
Definition at line 18 of file server_init.c.
Referenced by init_connection().
 {
         int rt = 0;
         int op = EPOLL_CTL_ADD;
         ev->events = EPOLLIN | EPOLLET;
         ev->data.fd = clisock;
         if (epoll_ctl(epollfd, op, clisock, ev) == -1) {
                 perror("set_clifd: epoll_ctl:");
                 rt = 84;
         }
         fprintf(stderr, "Add client n[%d] to epoll interest list\n", clisock);
         return (rt);
 }
set_epoll()
int set_epoll (t_serv * all)
Epoll IO handler initialisation
declare an epoll fd with epoll_create()
set event handling to EPOLLIN (check man epoll)
register server listening fd on ev structure
Definition at line 59 of file server_init.c.
References t_serv::epollfd, t_serv::ev, and t_serv::listen_sock.
Referenced by server().
 {
         int rt = 0;
         all->epollfd = epoll_create(10);
         memset(&all->ev, 0, sizeof(all->ev));
         if (all->epollfd == -1) {
                 perror("set_epoll: epoll_create1");
                 rt = 84;
         } else {
                 all->ev.events = EPOLLIN;
                 all->ev.data.fd = all->listen_sock;
                 rt = epoll_ctl(all->epollfd, EPOLL_CTL_ADD, all->listen_sock,
                         &all->ev);
                 if (rt == -1) {
                         perror("set_epoll: epoll_ctl");
                         rt = 84;
                 }
         }
         return (rt);
 }
set_iface()
int set_iface (adrinf * hints, adrinf ** res, const char * port)
Listening interface setup
Definition at line 34 of file server_init.c.
Referenced by server().
 {
         int rt = 0;
         memset(hints, 0, sizeof(struct addrinfo));
         hints->ai_family = AF_UNSPEC;
         hints->ai_socktype = SOCK_STREAM;
         hints->ai_flags = AI_PASSIVE;
         hints->ai_protocol = IPPROTO_TCP;
         hints->ai_canonname = NULL;
         hints->ai_addr = NULL;
         hints->ai_next = NULL;
         if ((getaddrinfo(NULL, port, hints, res))) {
                 perror("set_iface: getaddrinfo");
                 rt = 84;
         }
         return (rt);
 }
set_opts()
clargs* set_opts ()
Note
see server_src/cl_args_helpers.c
The flags 'gatherer' initialiser
Returns
opts the flags function pointer malloc'ed and assigned
Definition at line 27 of file cl_args_helpers.c.
References get_clientsNb(), get_freq(), get_height(), get_port(), get_teams(), and get_width().
Referenced by get_opts().
 {
         clargs *opts = malloc(sizeof(clargs) * 'z');
         opts['p'] = get_port;
         opts['x'] = get_width;
         opts['y'] = get_height;
         opts['n'] = get_teams;
         opts['c'] = get_clientsNb;
         opts['f'] = get_freq;
         return (opts);
 }
set_sockfd()
int set_sockfd (t_serv * all)
Note
see server_src/inits.c
Tcp Listening socket setup
declare a socket with socket()
bind() to an interface
listen() on this fd / socket
Parameters
all the 'foure tout' structure containing the struct to setup
Returns
sfd the configured listening socket fd or -1 if failure
Definition at line 100 of file server_init.c.
References BACKLOG, prevent_reused(), t_serv::res, and t_serv::rp.
Referenced by server().
 {
         int sfd = -1;
         for (all->rp = all->res; all->rp != NULL; all->rp = all->rp->ai_next) {
                 sfd = socket(all->rp->ai_family, all->rp->ai_socktype,
                         all->rp->ai_protocol);
                 prevent_reused(sfd);
                 if (sfd == -1) {
                         continue;
                 }
                 if (bind(sfd, all->rp->ai_addr, all->rp->ai_addrlen) == 0) {
                         break;
                 }
                 close(sfd);
         }
         if (all->rp == NULL) {
                 fprintf(stderr, "Could not bind\n");
         } else if ((listen(sfd, BACKLOG) == -1)) {
                 perror("listen: set_sockfd");
         }
         return (sfd);
 }
sig_handler()
void sig_handler (int signo)
Note
see server_src/signal_handler.c
Dummy signal hander to exit server properly on console with CTRL-C
Parameters
signo the catched signal type (hit man 2 signal)
Definition at line 15 of file sig_handler.c.
Referenced by main().
 {
         if (signo == SIGINT) {
                 printf("\nReceived SIGINT\n\tSee u !..\n");
                 exit(0);
         }
 }
usage()
void usage (char * progname)
Note
see server_src/usage.c
Definition at line 10 of file usage.c.
Referenced by main().
 {
         printf("USAGE: %s", progname);
         printf(" -p port -x width -y height -n name1 name2 ... ");
         printf("-c clientsNb -f freq\n");
         printf("\tport\t\tis the port number\n");
         printf("\twidth\t\tis the width of the world\n");
         printf("\theight\t\tis the height of the world\n");
         printf("\tnameX\t\tis the name of the team X\n");
         printf("\tclientNb\tis the number of authorized client per team\n");
         printf("\tclientNb\tis the reciprocal of time unit for execution ");
         printf("of actions\n");
 }
user()
void* user (cmdargs args, int clifd, t_teams * chans)
The USER <username> <mode> <unusued> <realname> command handler
Parameters
args the JOIN arguments, composed of the above args
clifd the client file descriptor
chans the main teams doubly linked list, updated by pushback'ing the new user in chan->users list
Returns
chans the head pointer of the teams list passed in params
Note
Still missing a lot of check for size, dublons etc etc and also the <mode> handling (invisible etc) see RFC 2812 part 3.1.3
Definition at line 83 of file rfc_cmds0.c.
References get_new_user(), get_new_userlist(), get_size(), insert_back_user(), and t_teams::users.
 {
         char *banneer = "|| Welcome to BrokenIRC Network || ";
         if (get_size(args) == 5) {
                 t_user *usr = get_new_user(clifd, args);
                 t_userlist *list = get_new_userlist(usr);
                 chans->users = insert_back_user(chans->users, list);
                 dprintf(clifd, "001 :%s %s %s\r\n", args[1], args[1], banneer);
         }
         return (chans);
 }
Variable Documentation
G_CMDS
const cmds G_CMDS[REF_NB]
The global pointer for subject commands methods
The functions pointers for the various RFC commands handlers
Definition at line 18 of file server_decls.c.
Referenced by get_methods().
G_PROTOS
const char* G_PROTOS[REF_NB]
The object prototype mapping the methods name
Note
see server_src/server_decls.c
The 2D array containing the handled commands strings for comparison
Definition at line 12 of file server_decls.c.
Referenced by get_methods().