PSU_zappy_2017: server/src/tcpserver_functions/server_init.c File Reference
server_init.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include "server.h"
Functions
int set_clifd (int clisock, int epollfd, struct epoll_event *ev)
int set_iface (adrinf *hints, adrinf **res, const char *port)
int set_epoll (t_serv *all)
static void prevent_reused (int sockfd)
int set_sockfd (t_serv *all)
Function Documentation
prevent_reused()
static void prevent_reused (int sockfd) static
Prevents those dreaded "Address already in use" errors
Definition at line 82 of file server_init.c.
Referenced by set_sockfd().
 {
         int yes = 1;
         if (setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR, (const void *)&yes,
                 sizeof(int)) == -1) {
                 perror("prevent_reused: setsockopt");
                 exit(84);
         }
 }
set_clifd()
int set_clifd (int clisock, int epollfd, struct epoll_event * ev)
Add the new client file descriptor in struct epoll_event structure for polling their events
Todo:
read this medium blog post on 'epoll madness'
Definition at line 17 of file server_init.c.
Referenced by init_connection().
 {
         int rt = 0;
         int op = EPOLL_CTL_ADD;
         ev->events = EPOLLIN | EPOLLET;
         ev->data.fd = clisock;
         if (epoll_ctl(epollfd, op, clisock, ev) == -1) {
                 perror("set_clifd: epoll_ctl:");
                 rt = 84;
         }
         fprintf(stderr, "Add client n°[%d] to epoll interest list\n", clisock);
         return (rt);
 }
set_epoll()
int set_epoll (t_serv * all)
Epoll IO handler initialisation
declare an epoll fd with epoll_create()
set event handling to EPOLLIN (check man epoll)
register server listening fd on ev structure
Parameters
all the foure tout structure
Definition at line 59 of file server_init.c.
References t_serv::epollfd, t_serv::ev, and t_serv::listen_sock.
Referenced by server().
 {
         int rt = 0;
         all->epollfd = epoll_create(10);
         memset(&all->ev, 0, sizeof(all->ev));
         if (all->epollfd == -1) {
                 perror("set_epoll: epoll_create1");
                 rt = 84;
         } else {
                 all->ev.events = EPOLLIN;
                 all->ev.data.fd = all->listen_sock;
                 rt = epoll_ctl(all->epollfd, EPOLL_CTL_ADD, all->listen_sock,
                         &all->ev);
                 if (rt == -1) {
                         perror("set_epoll: epoll_ctl");
                         rt = 84;
                 }
         }
         return (rt);
 }
set_iface()
int set_iface (adrinf * hints, adrinf ** res, const char * port)
Listening interface setup
Definition at line 33 of file server_init.c.
Referenced by server().
 {
         int rt = 0;
         memset(hints, 0, sizeof(struct addrinfo));
         hints->ai_family = AF_UNSPEC;
         hints->ai_socktype = SOCK_STREAM;
         hints->ai_flags = AI_PASSIVE;
         hints->ai_protocol = IPPROTO_TCP;
         hints->ai_canonname = NULL;
         hints->ai_addr = NULL;
         hints->ai_next = NULL;
         if ((getaddrinfo(NULL, port, hints, res))) {
                 perror("set_iface: getaddrinfo");
                 rt = 84;
         }
         return (rt);
 }
set_sockfd()
int set_sockfd (t_serv * all)
Tcp Listening socket setup
declare a socket with socket()
bind() to an interface
listen() on this fd / socket
Parameters
all the 'foure tout' structure containing the struct to setup
Returns
sfd the configured listening socket fd or -1 if failure
Definition at line 100 of file server_init.c.
References BACKLOG, prevent_reused(), t_serv::res, and t_serv::rp.
Referenced by server().
 {
         int sfd = -1;
         for (all->rp = all->res; all->rp != NULL; all->rp = all->rp->ai_next) {
                 sfd = socket(all->rp->ai_family, all->rp->ai_socktype,
                         all->rp->ai_protocol);
                 prevent_reused(sfd);
                 if (sfd == -1) {
                         continue;
                 }
                 if (bind(sfd, all->rp->ai_addr, all->rp->ai_addrlen) == 0) {
                         break;
                 }
                 close(sfd);
         }
         if (all->rp == NULL) {
                 fprintf(stderr, "Could not bind\n");
         } else if ((listen(sfd, BACKLOG) == -1)) {
                 perror("listen: set_sockfd");
         }
         return (sfd);
 }