PSU_zappy_2017: server_src/teams_list.c File Reference
teams_list.c File Reference
#include "../include/server.h"
#include <stdlib.h>
Functions
t_teams * get_new_chan_list (t_userlist *userlist, char *team_name)
void * insert_back_teams (t_teams *head, t_teams *new)
void remove_teams (t_teams *list, char *team_name)
void free_teams_list (t_teams *list)
t_teams * init_default_teams (void)
Function Documentation
free_teams_list()
void free_teams_list (t_teams * list)
Self explanatory
Parameters
list the list to be de-allocated
Definition at line 74 of file teams_list.c.
References free_userlist(), t_teams::next, and t_teams::users.
 {
         while (list) {
                 free_userlist(list->users);
                 t_teams *next = list->next;
                 free(list);
                 list = next;
         }
 }
get_new_chan_list()
t_teams* get_new_chan_list (t_userlist * userlist, char * team_name)
Self explanatory
Parameters
userlist the userlist to insert in the new teams element
team_name the new teams name
Definition at line 15 of file teams_list.c.
References MAX_TEAM_NAME, t_teams::next, t_teams::prev, t_teams::team_name, and t_teams::users.
Referenced by join().
 {
         t_teams *list = malloc(sizeof(*list));
         if (list) {
                 memset(list, 0, sizeof(*list));
                 list->users = userlist;
                 strncpy(list->team_name, team_name, MAX_TEAM_NAME);
                 list->prev = NULL;
                 list->next = NULL;
         }
         return (list);
 }
init_default_teams()
t_teams* init_default_teams (void)
Self explanatory
Returns
the default teams where all user resides
Note
the teams name, the default user and all could be parsed from a config file (#pullrequestIdea)
Definition at line 89 of file teams_list.c.
References get_new_user(), get_new_userlist(), t_teams::next, t_teams::prev, t_teams::team_name, and t_teams::users.
Referenced by get_methods().
 {
         char *defuser[5] = {"NICK", "4Dm1n", "42", "*", ":John Doe"};
         t_teams *defchan = malloc(sizeof(*defchan));
         t_user *admin = get_new_user(0, defuser);
         t_userlist *allusers = get_new_userlist(admin);
         if (defchan && admin && allusers) {
                 strcpy(defchan->team_name, "DEFTEAM");
                 defchan->users = allusers;
                 defchan->prev = NULL;
                 defchan->next = NULL;
         }
         return (defchan);
 }
insert_back_teams()
void* insert_back_teams (t_teams * head, t_teams * new)
Push back a new teams element to the main list container
Parameters
head the head pointer
new the new teams element to be inserted
Definition at line 33 of file teams_list.c.
References t_teams::next.
Referenced by join().
 {
         t_teams *tmp = head;
         if (!head) {
                 head = new;
         } else {
                 while (tmp->next) {
                         tmp = tmp->next;
                 }
                 tmp->next = new;
                 new->prev = tmp;
         }
         return (head);
 }
remove_teams()
void remove_teams (t_teams * list, char * team_name)
Remove a teams element from the doubly linked list
Parameters
list the userlist to be updated
team_name the teams name to be deleted
Definition at line 53 of file teams_list.c.
References free_userlist(), t_teams::next, t_teams::prev, t_teams::team_name, and t_teams::users.
 {
         t_teams *tmp = list;
         while (tmp->next != NULL)
         {
                 if (!strcmp(tmp->team_name, team_name)) {
                         tmp->prev->next = tmp->next;
                         tmp->next->prev = tmp->prev;
                         free_userlist(tmp->users);
                         free(tmp->team_name);
                         free(tmp);
                         break;
                 }
                 tmp = tmp->next;
         }
 }