PSU_zappy_2017: server/src/trantor_setup/teams_mgr.c File Reference
teams_mgr.c File Reference
#include "../../include/server.h"
Functions
t_teams * get_new_team (char *name)
t_teams * add_team_back (t_teams *list, char *name)
t_teams * init_teams (char **teams_names)
Function Documentation
add_team_back()
t_teams* add_team_back (t_teams * list, char * name)
Definition at line 24 of file teams_mgr.c.
References get_new_team(), t_teams::next, and t_teams::prev.
Referenced by init_teams().
 {
         t_teams *new_team = get_new_team(name);
         if (new_team && list) {
                 new_team->prev = list;
                 list->next = new_team;
         }
         return new_team;
 }
get_new_team()
t_teams* get_new_team (char * name)
Note
all trantor setup command and fctions trantor_setup/teams_mgr.c
Definition at line 10 of file teams_mgr.c.
References t_teams::next, t_teams::prev, t_teams::team_name, and t_teams::users.
Referenced by add_team_back(), and init_teams().
 {
         t_teams *list = malloc(sizeof(*list));
         if (list) {
                 memset(list, 0, sizeof(*list));
                 list->users = NULL;
                 list->team_name = strdup(name);
                 list->next = NULL;
                 list->prev = NULL;
         }
         return list;
 }
init_teams()
t_teams* init_teams (char ** teams_names)
Definition at line 35 of file teams_mgr.c.
References add_team_back(), get_new_team(), and t_teams::prev.
Referenced by get_world().
 {
         int i;
         t_teams *teamlist = get_new_team(teams_names[0]);
         for (i = 1; teams_names[i]; i++) {
                 teamlist = add_team_back(teamlist, teams_names[i]);
         }
         while (teamlist->prev)
                 teamlist = teamlist->prev;
         return teamlist;
 }