PSU_zappy_2017: server_src/send_fcts/time.c File Reference
time.c File Reference
#include "cmd_fcts.h"
Functions
void * send_inc_start (cmdargs args, int clifd, t_teams *teams)
void * send_inc_end (cmdargs args, int clifd, t_teams *teams)
void * send_time_unit (cmdargs args, int clifd, t_teams *teams)
void * send_time_modif (cmdargs args, int clifd, t_teams *teams)
Function Documentation
send_inc_end()
void* send_inc_end (cmdargs args, int clifd, t_teams * teams)
Definition at line 40 of file time.c.
References find_user_in_teams(), t_userlist::next, and t_teams::next.
 {
         int pos[2];
         t_user *incantor = find_user_in_teams(teams, clifd);
         pos[0] = incantor->refplayer->curr_pos[0];
         pos[1] = incantor->refplayer->curr_pos[1];
         for (t_teams *tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (t_userlist *tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                         dprintf(tmpu->user->clifd, "pie %d %d %s",
                                 pos[0], pos[1], args[0]);
                 }
         }
 }
send_inc_start()
void* send_inc_start (cmdargs args, int clifd, t_teams * teams)
Definition at line 11 of file time.c.
References find_user_in_teams(), get_nbr_by_level(), t_inhabitant::level, t_userlist::next, t_teams::next, teams, tile, t_tile::trantorians, x, and y.
 {
         t_user *incantor = find_user_in_teams(teams, clifd);
         int x = incantor->refplayer->curr_pos[0];
         int y = incantor->refplayer->curr_pos[1];
         t_tile *tile = teams->refmap->tiles[x][y];
         t_inhabitant *player;
         int req_lvl = incantator->refplayer->level;
         char *nums = malloc(2 * get_nbr_by_level(req_lvl));
         for (player = tile->trantorians; player; player = player->next) {
                 if (player->level == incantor->refplayer->level) {
                         nums = strcat(nums, " ");
                         nums = strcat(nums, tmpu->user->refplayer->id);
                 }
         }
         for (t_teams *tmpt = teams; tmpt; tmpt = tmpt->next) {
                 for (t_userlist *tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                         dprintf(tmpu->user->clifd, "pic %d %d %d%s\n",
                                 pos[0], pos[1], req_lvl, nums);
                 }
         }
         free(nums);
         return teams;
 }
send_time_modif()
void* send_time_modif (cmdargs args, int clifd, t_teams * teams)
Definition at line 64 of file time.c.
 {
         dprintf(clifd, "sst %d\n", teams->refmap->freq);
 }
send_time_unit()
void* send_time_unit (cmdargs args, int clifd, t_teams * teams)
Definition at line 56 of file time.c.
 {
         dprintf(clifd, "sgt %d\n", teams->refmap->freq);
 }