PSU_zappy_2017Server: server_src/user_list.c File Reference
user_list.c File Reference
#include "../include/server.h"
#include <stdlib.h>
Functions
t_user * get_new_user (int clifd, cmdargs usercmd)
t_userlist * get_new_userlist (t_user *usr)
void * insert_back_user (t_userlist *head, t_userlist *nuser)
void * remove_user (t_userlist *list, int clifd)
void free_userlist (t_userlist *list)
Function Documentation
free_userlist()
void free_userlist (t_userlist * list)
Self explanatory
Parameters
list the list to be freed
Definition at line 98 of file user_list.c.
References t_userlist::next, t_user::nick, t_user::rname, and t_userlist::user.
Referenced by free_teams_list(), and remove_teams().
 {
         while (list) {
                 free(list->user->rname);
                 free(list->user->nick);
                 free(list->user);
                 t_userlist *next = list->next;
                 free(list);
                 list = next;
         }
 }
get_new_user()
t_user* get_new_user (int clifd, cmdargs usercmd)
Malloc and memset a new t_user element
Parameters
clifd the user client file descriptor
usercmd the USER <space> args 2d array
Returns
list the new element
Definition at line 16 of file user_list.c.
References t_user::clifd, t_user::mode, t_user::nick, and t_user::rname.
Referenced by init_default_teams(), and user().
 {
         t_user *usr = malloc(sizeof(*usr));
         if (usr) {
                 memset(usr, 0, sizeof(*usr));
                 usr->clifd = clifd;
                 usr->mode = atoi(usercmd[2]);
                 usr->nick = strdup(usercmd[1]);
                 usr->rname = strdup(usercmd[4]);
         }
         return (usr);
 }
get_new_userlist()
t_userlist* get_new_userlist (t_user * usr)
Malloc and memset a new userlist element
Parameters
usr the t_user on the userlist
Returns
list the new element
Definition at line 34 of file user_list.c.
References t_userlist::next, t_userlist::prev, and t_userlist::user.
Referenced by init_default_teams(), join(), and user().
 {
         t_userlist *list = malloc(sizeof(*list));
         if (list) {
                 memset(list, 0, sizeof(*list));
                 list->user = usr;
                 list->prev = NULL;
                 list->next = NULL;
         }
         return (list);
 }
insert_back_user()
void* insert_back_user (t_userlist * head, t_userlist * nuser)
Push back a n(ew)user in the userlist head
Parameters
head the userlist to be modified
nuser the n(ew)user to be inserted
Returns
head the head pointer
Definition at line 52 of file user_list.c.
References t_userlist::next, and t_userlist::prev.
Referenced by join(), and user().
 {
         t_userlist *tmp = head;
         if (!head) {
                 head = nuser;
         } else {
                 while (tmp->next) {
                         tmp = tmp->next;
                 }
                 tmp->next = nuser;
                 nuser->prev = tmp;
         }
         return (head);
 }
remove_user()
void* remove_user (t_userlist * list, int clifd)
Remove a user from a userlist
Parameters
list the userlist to be updated
clifd the clientfd as index for element to be removed
Returns
list the updated userlist
Definition at line 73 of file user_list.c.
References t_user::clifd, t_userlist::next, t_user::nick, t_userlist::prev, t_user::rname, and t_userlist::user.
 {
         t_userlist *tmp = list;
         while (tmp) {
                 if (tmp->user->clifd == clifd) {
                         tmp->prev->next = tmp->next;
                         if (tmp->next)
                                 tmp->next->prev = tmp->prev;
                         else
                                 tmp->next = NULL;
                         free(tmp->user->rname);
                         free(tmp->user->nick);
                         free(tmp->user);
                         free(tmp);
                         break;
                 }
                 tmp = tmp->next;
         }
         return (list);
 }