PSU_zappy_2017: server/src/send_fcts/utils.c File Reference
utils.c File Reference
#include "cmd_fcts.h"
Functions
void move (t_inhabitant *player, t_world *map)
int assign_player (char *team_name, t_teams *teams, int clifd)
int count_nb_empty (t_teams *teams, char *team_name)
void * add_obj_to_player (t_inhabitant *player, char *obj_name)
int check_obj_on_map (t_world *map, int x, int y, char *obj_name)
Function Documentation
add_obj_to_player()
void* add_obj_to_player (t_inhabitant * player, char * obj_name)
Definition at line 74 of file utils.c.
References t_ressources::deraumere, t_ressources::food, t_inhabitant::inventory, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_ressources::sibur, and t_ressources::thystame.
Referenced by r_take_obj().
 {
         t_stone *stones[6] = {&player->inventory.sibur,
                               &player->inventory.phiras,
                               &player->inventory.mendiane,
                               &player->inventory.thystame,
                               &player->inventory.linemate,
                               &player->inventory.deraumere};
         if (strcmp(player->inventory.food.name, obj_name) == 0) {
                 player->inventory.food.qtt += 1;
         }
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         stones[i]->qtt += 1;
                         break;
                 }
         }
         return player;
 }
assign_player()
int assign_player (char * team_name, t_teams * teams, int clifd)
Definition at line 40 of file utils.c.
References t_userlist::next, and t_teams::next.
Referenced by r_team().
 {
         int exist = false;
         for (t_teams *tmpt = teams; tmpt; tmpt = tmpt->next) {
                 if (strcmp(team_name, tmpt->team_name) == 0) {
                         for (t_userlist *tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                                 if (!tmpu->user->isco) {
                                         exist = true;
                                         tmpu->user->clifd = clifd;
                                         tmpu->user->isco = true;
                                         break;
                                 }
                         }
                 }
         }
         return exist;
 }
check_obj_on_map()
int check_obj_on_map (t_world * map, int x, int y, char * obj_name)
Definition at line 95 of file utils.c.
References t_ressources::deraumere, t_ressources::food, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_food::qtt, t_tile::ressources, t_ressources::sibur, t_ressources::thystame, t_world::tiles, x, and y.
Referenced by r_take_obj().
 {
         t_stone *stones[6] = {&map->tiles[x][y].ressources.sibur,
                               &map->tiles[x][y].ressources.phiras,
                               &map->tiles[x][y].ressources.mendiane,
                               &map->tiles[x][y].ressources.thystame,
                               &map->tiles[x][y].ressources.linemate,
                               &map->tiles[x][y].ressources.deraumere};
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         if (stones[i]->qtt > 0)
                                 return true;
                 }
         }
         if (strcmp(map->tiles[x][y].ressources.food.name, obj_name) == 0) {
                 printf("There is food on this tile\n");
                 if (map->tiles[x][y].ressources.food.qtt > 0)
                         return true;
         }
         return false;
 }
count_nb_empty()
int count_nb_empty (t_teams * teams, char * team_name)
Definition at line 59 of file utils.c.
References t_userlist::next, and t_teams::next.
Referenced by r_connect_nbr(), and r_team().
 {
         int nb_empty = 0;
         for (t_teams *tmpt = teams; tmpt; tmpt = tmpt->next) {
                 if (strcmp(team_name, tmpt->team_name) == 0) {
                         for (t_userlist *tmpu = tmpt->users; tmpu; tmpu = tmpu->next) {
                                 if (!tmpu->user->isco)
                                         nb_empty++;
                         }
                 }
         }
         return nb_empty;
 }
move()
void move (t_inhabitant * player, t_world * map)
see send_fcts/utils.c
Definition at line 10 of file utils.c.
References t_inhabitant::curr_pos, E, N, t_inhabitant::o, S, t_world::sizeX, t_world::sizeY, and W.
Referenced by r_forward().
 {
         switch (player->o) {
         case N:
                 if (player->curr_pos[1] == (map->sizeY - 1))
                         player->curr_pos[1] -= (map->sizeY - 1);
                 else
                         player->curr_pos[1] += 1;
                 break;
         case E:
                 if (player->curr_pos[0] == (map->sizeX - 1))
                         player->curr_pos[0] -= (map->sizeX - 1);
                 else
                         player->curr_pos[0] += 1;
                 break;
         case S:
                 if (player->curr_pos[1] == (map->sizeY - 1))
                         player->curr_pos[1] += (map->sizeY - 1);
                 else
                         player->curr_pos[1] -= 1;
                 break;
         case W:
                 if (player->curr_pos[1] == (map->sizeY - 1))
                         player->curr_pos[1] -= (map->sizeY - 1);
                 else
                         player->curr_pos[0] -= 1;
                 break;
         }
 }