PSU_zappy_2017: server/src/send_fcts/utils2.c File Reference
utils2.c File Reference
#include "cmd_fcts.h"
Functions
void * del_obj_on_map (t_world *map, int x, int y, char *obj_name)
int check_obj_in_inv (t_inhabitant *player, char *obj_name)
void * del_obj_from_player (t_inhabitant *player, char *obj_name)
void * add_obj_to_map (t_world *map, int x, int y, char *obj_name)
Function Documentation
add_obj_to_map()
void* add_obj_to_map (t_world * map, int x, int y, char * obj_name)
Definition at line 73 of file utils2.c.
References t_ressources::deraumere, t_ressources::food, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_tile::ressources, t_ressources::sibur, t_ressources::thystame, and t_world::tiles.
Referenced by r_set_obj().
 {
         t_stone *stones[6] = {&map->tiles[x][y].ressources.sibur,
                               &map->tiles[x][y].ressources.phiras,
                               &map->tiles[x][y].ressources.mendiane,
                               &map->tiles[x][y].ressources.thystame,
                               &map->tiles[x][y].ressources.linemate,
                               &map->tiles[x][y].ressources.deraumere};
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         stones[i]->qtt += 1;
                         break;
                 }
         }
         if (strcmp(map->tiles[x][y].ressources.food.name, obj_name) == 0) {
                 map->tiles[x][y].ressources.food.qtt += 1;
         }
         return map;
 }
check_obj_in_inv()
int check_obj_in_inv (t_inhabitant * player, char * obj_name)
Definition at line 30 of file utils2.c.
References t_ressources::deraumere, t_ressources::food, t_inhabitant::inventory, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_food::qtt, t_ressources::sibur, and t_ressources::thystame.
Referenced by r_set_obj().
 {
         t_stone *stones[6] = {&player->inventory.sibur,
                               &player->inventory.phiras,
                               &player->inventory.mendiane,
                               &player->inventory.thystame,
                               &player->inventory.linemate,
                               &player->inventory.deraumere};
         if (strcmp(player->inventory.food.name, obj_name) == 0) {
                 if (player->inventory.food.qtt > 0)
                         return true;
         }
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         if (stones[i]->qtt > 0)
                                 return true;
                 }
         }
         return false;
 }
del_obj_from_player()
void* del_obj_from_player (t_inhabitant * player, char * obj_name)
Definition at line 52 of file utils2.c.
References t_ressources::deraumere, t_ressources::food, t_inhabitant::inventory, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_ressources::sibur, and t_ressources::thystame.
Referenced by r_set_obj().
 {
         t_stone *stones[6] = {&player->inventory.sibur,
                               &player->inventory.phiras,
                               &player->inventory.mendiane,
                               &player->inventory.thystame,
                               &player->inventory.linemate,
                               &player->inventory.deraumere};
         if (strcmp(player->inventory.food.name, obj_name) == 0) {
                 player->inventory.food.qtt -= 1;
         }
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         stones[i]->qtt -= 1;
                         break;
                 }
         }
         return player;
 }
del_obj_on_map()
void* del_obj_on_map (t_world * map, int x, int y, char * obj_name)
see send_fcts/utils2.c
Definition at line 10 of file utils2.c.
References t_ressources::deraumere, t_ressources::food, t_ressources::linemate, t_ressources::mendiane, t_food::name, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_tile::ressources, t_ressources::sibur, t_ressources::thystame, and t_world::tiles.
Referenced by r_take_obj().
 {
         t_stone *stones[6] = {&map->tiles[x][y].ressources.sibur,
                               &map->tiles[x][y].ressources.phiras,
                               &map->tiles[x][y].ressources.mendiane,
                               &map->tiles[x][y].ressources.thystame,
                               &map->tiles[x][y].ressources.linemate,
                               &map->tiles[x][y].ressources.deraumere};
         for (int i = 0; i < 6; i++) {
                 if (strcmp(stones[i]->name, obj_name) == 0) {
                         stones[i]->qtt -= 1;
                         break;
                 }
         }
         if (strcmp(map->tiles[x][y].ressources.food.name, obj_name) == 0) {
                 map->tiles[x][y].ressources.food.qtt -= 1;
         }
         return map;
 }