PSU_zappy_2017: server/src/trantor_setup/world_creation.c File Reference
world_creation.c File Reference
#include <stdlib.h>
#include <time.h>
#include "../../include/server.h"
Functions
void free_world (t_world *trantor, t_clargs *args)
static void get_ressources (t_ressources *tileress)
static t_tile ** get_tiles (int x, int y)
t_world * get_world (t_clargs *args)
Function Documentation
free_world()
void free_world (t_world * trantor, t_clargs * args)
Free the t_world ptr with the 2D t_tile array inside
Parameters
trantor the world pointer to be freed
args the command line args to have the map size
Definition at line 16 of file world_creation.c.
References t_clargs::height, and t_world::tiles.
Referenced by get_world(), and server().
 {
         t_tile **tmp = trantor->tiles;
         for (int i = 0; i < args->height; ++i) {
                 free(tmp[i]);
         }
         free(tmp);
         free(trantor);
 }
get_ressources()
static void get_ressources (t_ressources * tileress) static
Assign random qtt of ITEMS in each world tile
Parameters
tileress a pointer to a tile ressource structure
Definition at line 30 of file world_creation.c.
References t_ressources::deraumere, t_ressources::food, ITEMS, t_ressources::linemate, MAX_RAND, t_ressources::mendiane, t_ressources::phiras, t_stone::qtt, t_food::qtt, t_ressources::sibur, and t_ressources::thystame.
Referenced by get_tiles().
 {
         memcpy(tileress, &ITEMS, sizeof(ITEMS));
         tileress->food.qtt = rand()%(MAX_RAND-0)+0;
         tileress->linemate.qtt = rand()%(MAX_RAND-0)+0;
         tileress->deraumere.qtt = rand()%(MAX_RAND-0)+0;
         tileress->sibur.qtt = rand()%(MAX_RAND-0)+0;
         tileress->mendiane.qtt = rand()%(MAX_RAND-0)+0;
         tileress->phiras.qtt = rand()%(MAX_RAND-0)+0;
         tileress->thystame.qtt = rand()%(MAX_RAND-0)+0;
 }
get_tiles()
static t_tile** get_tiles (int x, int y) static
Alloc memory and fill with ressource the t_world::tiles
Parameters
x the map width
y the map height
Returns
tiles the 2D tiles array
Definition at line 47 of file world_creation.c.
References get_ressources(), x, and y.
Referenced by get_world().
 {
         t_tile  **tiles = malloc(sizeof(*tiles) * y);
         int     i = 0;
         int     j = 0;
         if (tiles) {
                 srand(time(NULL));
                 for (i = 0; i < y; ++i) {
                         tiles[i] = malloc(sizeof(*tiles[i]) * x);
                         for (j = 0; j < x; ++j) {
                                 get_ressources(&tiles[i][j].ressources);
                         }
                 }
         }
         return (tiles);
 }
get_world()
t_world* get_world (t_clargs * args)
Setup the trantor world map
Parameters
args the args pointer containing the map size
Returns
trantor the setup'ed map
Definition at line 69 of file world_creation.c.
References t_ressources::food, free_world(), get_tiles(), get_world(), t_clargs::height, init_teams(), init_userlist(), main(), t_food::qtt, t_tile::ressources, t_world::sizeX, t_world::sizeY, t_world::teams, t_clargs::teams_names, t_world::tiles, and t_clargs::width.
Referenced by get_world(), and server().
 {
         t_world *trantor = malloc(sizeof(*trantor));
         if (trantor) {
                 trantor->sizeX = args->width;
                 trantor->sizeY = args->height;
                 trantor->teams = init_teams(args->teams_names);
                 trantor->teams = init_userlist(trantor->teams, args);
                 trantor->tiles = get_tiles(args->width, args->height);
         }
         return (trantor);
 }